// docs/src/components/tools/phone-book-editor/shared/RowsEditor.svelte
<script lang="ts" generics="Row extends Record<string, string>">
	export interface RowsEditorColumn {
		key: string;
		label: string;
		placeholder?: string;
	}

	interface Props {
		rows: Row[];
		columns: RowsEditorColumn[];
		createEmpty: () => Row;
		minRows?: number;
		addLabel?: string;
	}

	let {
		rows = $bindable(),
		columns,
		createEmpty,
		minRows = 1,
		addLabel = '+ Add row'
	}: Props = $props();

	let twoCol = $derived(columns.length === 2);

	function remove(index: number) {
		if (rows.length <= minRows) return;
		rows.splice(index, 1);
	}
</script>

<div>
	<div class="pbRowsTable">
		<div class="pbRowsHeader" class:pbRowTwoCol={twoCol} class:pbRowOneCol={!twoCol}>
			{#each columns as c (c.key)}
				<span>{c.label}</span>
			{/each}
			<span></span>
		</div>
		{#each rows as row, i (i)}
			<div class="pbRow" class:pbRowTwoCol={twoCol} class:pbRowOneCol={!twoCol}>
				{#each columns as c (c.key)}
					<input
						type="text"
						class="ceInput"
						value={row[c.key] ?? ''}
						placeholder={c.placeholder}
						aria-label="{c.label} {i + 1}"
						oninput={(e) => ((row as Record<string, string>)[c.key] = e.currentTarget.value)}
					/>
				{/each}
				<button
					type="button"
					class="ceArrayRemoveBtn"
					onclick={() => remove(i)}
					title="Remove row"
					disabled={rows.length <= minRows}
				>
					&times;
				</button>
			</div>
		{/each}
	</div>
	<button type="button" class="ceArrayAddBtn" onclick={() => rows.push(createEmpty())}>
		{addLabel}
	</button>
</div>

// docs/src/components/PhoneBookEditor/shared/RowsEditor.tsx
import React, { type ReactNode } from 'react';
import ceStyles from '../../ConfigEditor/ConfigEditor.module.css';
import styles from '../PhoneBookEditor.module.css';

export interface RowsEditorColumn {
	key: string;
	label: string;
	placeholder?: string;
}

interface RowsEditorProps<Row extends Record<string, string>> {
	rows: Row[];
	columns: RowsEditorColumn[];
	onChange: (rows: Row[]) => void;
	createEmpty: () => Row;
	minRows?: number;
	addLabel?: string;
}

export default function RowsEditor<Row extends Record<string, string>>({
	rows,
	columns,
	onChange,
	createEmpty,
	minRows = 1,
	addLabel = '+ Add row'
}: RowsEditorProps<Row>): ReactNode {
	const twoCol = columns.length === 2;
	const rowClass = `${styles.pbRow} ${twoCol ? styles.pbRowTwoCol : styles.pbRowOneCol}`;

	const update = (index: number, key: string, value: string) => {
		const copy = [...rows];
		copy[index] = { ...copy[index], [key]: value };
		onChange(copy);
	};

	const remove = (index: number) => {
		if (rows.length <= minRows) return;
		onChange(rows.filter((_, i) => i !== index));
	};

	const add = () => onChange([...rows, createEmpty()]);

	return (
		<div>
			<div className={styles.pbRowsTable}>
				<div
					className={`${styles.pbRowsHeader} ${twoCol ? styles.pbRowTwoCol : styles.pbRowOneCol}`}
				>
					{columns.map((c) => (
						<span key={c.key}>{c.label}</span>
					))}
					<span />
				</div>
				{rows.map((row, i) => (
					<div className={rowClass} key={i}>
						{columns.map((c) => (
							<input
								key={c.key}
								type="text"
								className={ceStyles.ceInput}
								value={row[c.key] ?? ''}
								placeholder={c.placeholder}
								onChange={(e) => update(i, c.key, e.target.value)}
							/>
						))}
						<button
							type="button"
							className={ceStyles.ceArrayRemoveBtn}
							onClick={() => remove(i)}
							title="Remove row"
							disabled={rows.length <= minRows}
						>
							&times;
						</button>
					</div>
				))}
			</div>
			<button type="button" className={ceStyles.ceArrayAddBtn} onClick={add}>
				{addLabel}
			</button>
		</div>
	);
}
