// docs/src/components/ConfigEditor/shared/LabelConfigEditor.tsx
import React from 'react';
import type { LabelFormState } from '@site/src/utils/configDefaults';
import styles from '../ConfigEditor.module.css';

interface LabelConfigEditorProps {
	label: string;
	value: LabelFormState;
	onChange: (value: LabelFormState) => void;
}

const LOCATIONS = ['BOTTOM_LEFT', 'BOTTOM_RIGHT', 'TOP_LEFT', 'TOP_RIGHT'];
const WEIGHTS = ['100', '200', '300', '400', '500', '600', '700', '800', '900'];

export default function LabelConfigEditor({ label, value, onChange }: LabelConfigEditorProps) {
	const update = (partial: Partial<LabelFormState>) => {
		onChange({ ...value, ...partial });
	};

	const updatePosition = (key: string, val: string) => {
		onChange({ ...value, POSITION: { ...value.POSITION, [key]: val } });
	};

	return (
		<div className={styles.ceSubSection}>
			<div className={styles.ceSubSectionTitle}>{label}</div>

			<div className={styles.ceCardGrid}>
				<div className={styles.ceFieldGroup}>
					<label className={styles.ceLabel}>Location</label>
					<select
						className={styles.ceSelect}
						value={value.LOCATION}
						onChange={(e) => update({ LOCATION: e.target.value })}
					>
						{LOCATIONS.map((loc) => (
							<option key={loc} value={loc}>
								{loc.replace(/_/g, ' ')}
							</option>
						))}
					</select>
				</div>

				<div className={styles.ceFieldGroup}>
					<label className={styles.ceLabel}>Text Size</label>
					<input
						type="text"
						className={`${styles.ceInput} ${styles.ceInputSmall}`}
						value={value.TEXT_SIZE}
						onChange={(e) => update({ TEXT_SIZE: e.target.value })}
						placeholder="14px"
					/>
				</div>

				<div className={styles.ceFieldGroup}>
					<label className={styles.ceLabel}>Font Weight</label>
					<select
						className={styles.ceSelect}
						value={value.TEXT_WEIGHT}
						onChange={(e) => update({ TEXT_WEIGHT: e.target.value })}
					>
						{WEIGHTS.map((w) => (
							<option key={w} value={w}>
								{w}
							</option>
						))}
					</select>
				</div>
			</div>

			<div className={styles.ceFieldGroup}>
				<label className={styles.ceLabel}>Position Offsets</label>
				<div className={styles.ceCardGrid}>
					{(['LEFT', 'RIGHT', 'UP', 'DOWN'] as const).map((dir) => (
						<div key={dir} style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
							<span style={{ fontSize: '0.75rem', minWidth: '40px' }}>{dir}</span>
							<input
								type="text"
								className={`${styles.ceInput} ${styles.ceInputSmall}`}
								value={value.POSITION[dir]}
								onChange={(e) => updatePosition(dir, e.target.value)}
								placeholder="0"
							/>
						</div>
					))}
				</div>
			</div>
		</div>
	);
}

// docs_new/src/components/tools/config-editor/shared/LabelConfigEditor.svelte
<script lang="ts">
	import type { LabelFormState } from '../../../../utils/configDefaults';

	interface Props {
		label: string;
		value: LabelFormState;
	}

	let { label, value = $bindable() }: Props = $props();

	const LOCATIONS = ['BOTTOM_LEFT', 'BOTTOM_RIGHT', 'TOP_LEFT', 'TOP_RIGHT'];
	const WEIGHTS = ['100', '200', '300', '400', '500', '600', '700', '800', '900'];
	const DIRECTIONS = ['LEFT', 'RIGHT', 'UP', 'DOWN'] as const;

	const id = $props.id();
</script>

<div class="ceSubSection">
	<div class="ceSubSectionTitle">{label}</div>

	<div class="ceCardGrid">
		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-location">Location</label>
			<select id="{id}-location" class="ceSelect" bind:value={value.LOCATION}>
				{#each LOCATIONS as loc (loc)}
					<option value={loc}>{loc.replace(/_/g, ' ')}</option>
				{/each}
			</select>
		</div>

		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-size">Text Size</label>
			<input
				id="{id}-size"
				type="text"
				class="ceInput ceInputSmall"
				bind:value={value.TEXT_SIZE}
				placeholder="14px"
			/>
		</div>

		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-weight">Font Weight</label>
			<select id="{id}-weight" class="ceSelect" bind:value={value.TEXT_WEIGHT}>
				{#each WEIGHTS as w (w)}
					<option value={w}>{w}</option>
				{/each}
			</select>
		</div>
	</div>

	<div class="ceFieldGroup">
		<span class="ceLabel">Position Offsets</span>
		<div class="ceCardGrid">
			{#each DIRECTIONS as dir (dir)}
				<div style="display: flex; align-items: center; gap: 0.375rem;">
					<label style="font-size: 0.75rem; min-width: 40px;" for="{id}-pos-{dir}">{dir}</label>
					<input
						id="{id}-pos-{dir}"
						type="text"
						class="ceInput ceInputSmall"
						bind:value={value.POSITION[dir]}
						placeholder="0"
					/>
				</div>
			{/each}
		</div>
	</div>
</div>
