// docs/src/components/tools/config-editor/sections/DescriptionSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';
	import I18nWrapper from '../shared/I18nWrapper.svelte';
	import type { DescriptionItemForm } from '../../../../utils/configDefaults';

	let config = $derived(configEditor.config);
</script>

{#snippet descriptionItems(items: DescriptionItemForm[], lang: string)}
	<div>
		{#each items as item, i (i)}
			<div class="ceCard">
				<div class="ceCardHeader">
					<span class="ceCardTitle">Item #{i + 1}</span>
					<button
						type="button"
						class="ceBtn ceBtnSmall ceBtnDanger"
						onclick={() => items.splice(i, 1)}
					>
						Remove
					</button>
				</div>
				<div class="ceCardGrid">
					<div class="ceFieldGroup">
						<label class="ceLabel" for="desc-{lang}-{i}-type">Type</label>
						<select id="desc-{lang}-{i}-type" class="ceSelect" bind:value={item.TYPE}>
							<option value="TEXT">Text</option>
							<option value="HTML">HTML</option>
							<option value="IMAGE">Image</option>
						</select>
					</div>
				</div>
				<div class="ceFieldGroup">
					<label class="ceLabel" for="desc-{lang}-{i}-content">Content</label>
					{#if item.TYPE === 'HTML'}
						<textarea
							id="desc-{lang}-{i}-content"
							class="ceTextarea"
							bind:value={item.CONTENT}
							placeholder="<p>Your description here</p>"></textarea>
					{:else}
						<input
							id="desc-{lang}-{i}-content"
							type="text"
							class="ceInput"
							bind:value={item.CONTENT}
							placeholder={item.TYPE === 'IMAGE' ? './assets/images/info.png' : 'Description text'}
						/>
					{/if}
				</div>
			</div>
		{/each}
		<button
			type="button"
			class="ceArrayAddBtn"
			onclick={() => items.push({ TYPE: 'HTML', CONTENT: '' })}
		>
			+ Add description item
		</button>
	</div>
{/snippet}

<AccordionSection
	id="section-description"
	title="Description"
	description="Content displayed in the Misc panel description area. Supports text, HTML, and image types with multilingual options."
	learnMoreHref="./guide-for-admins/customize-page#description"
>
	<I18nWrapper bind:state={config.DESCRIPTION} renderItems={descriptionItems} />
</AccordionSection>

// docs/src/components/ConfigEditor/sections/DescriptionSection.tsx
import React from 'react';
import { useConfigEditor } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import I18nWrapper from '../shared/I18nWrapper';
import type { DescriptionItemForm } from '@site/src/utils/configDefaults';
import styles from '../ConfigEditor.module.css';

export default function DescriptionSection() {
	const { state } = useConfigEditor();

	const renderItems = (
		items: DescriptionItemForm[],
		onChange: (items: DescriptionItemForm[]) => void
	) => {
		const updateItem = (index: number, partial: Partial<DescriptionItemForm>) => {
			const copy = items.map((d) => ({ ...d }));
			copy[index] = { ...copy[index], ...partial };
			onChange(copy);
		};

		const removeItem = (index: number) => {
			onChange(items.filter((_, i) => i !== index));
		};

		const addItem = () => {
			onChange([...items, { TYPE: 'HTML', CONTENT: '' }]);
		};

		return (
			<div>
				{items.map((item, i) => (
					<div key={i} className={styles.ceCard}>
						<div className={styles.ceCardHeader}>
							<span className={styles.ceCardTitle}>Item #{i + 1}</span>
							<button
								type="button"
								className={`${styles.ceBtn} ${styles.ceBtnSmall} ${styles.ceBtnDanger}`}
								onClick={() => removeItem(i)}
							>
								Remove
							</button>
						</div>
						<div className={styles.ceCardGrid}>
							<div className={styles.ceFieldGroup}>
								<label className={styles.ceLabel}>Type</label>
								<select
									className={styles.ceSelect}
									value={item.TYPE}
									onChange={(e) => updateItem(i, { TYPE: e.target.value })}
								>
									<option value="TEXT">Text</option>
									<option value="HTML">HTML</option>
									<option value="IMAGE">Image</option>
								</select>
							</div>
						</div>
						<div className={styles.ceFieldGroup}>
							<label className={styles.ceLabel}>Content</label>
							{item.TYPE === 'HTML' ? (
								<textarea
									className={styles.ceTextarea}
									value={item.CONTENT}
									onChange={(e) => updateItem(i, { CONTENT: e.target.value })}
									placeholder="<p>Your description here</p>"
								/>
							) : (
								<input
									type="text"
									className={styles.ceInput}
									value={item.CONTENT}
									onChange={(e) => updateItem(i, { CONTENT: e.target.value })}
									placeholder={
										item.TYPE === 'IMAGE' ? './assets/images/info.png' : 'Description text'
									}
								/>
							)}
						</div>
					</div>
				))}
				<button type="button" className={styles.ceArrayAddBtn} onClick={addItem}>
					+ Add description item
				</button>
			</div>
		);
	};

	return (
		<AccordionSection
			id="section-description"
			title="Description"
			description="Content displayed in the Misc panel description area. Supports text, HTML, and image types with multilingual options."
			learnMoreHref="./guide-for-admins/customize-page#description"
		>
			<I18nWrapper basePath={['DESCRIPTION']} state={state.DESCRIPTION} renderItems={renderItems} />
		</AccordionSection>
	);
}
