// docs/src/components/tools/config-editor/sections/InitialSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';
	import StringArrayEditor from '../shared/StringArrayEditor.svelte';

	const PANELS = ['phone', 'graph', 'equalizer', 'misc'];
	let config = $derived(configEditor.config);
	const id = $props.id();
</script>

<AccordionSection
	id="section-initial"
	title="Initial Settings"
	description="Phones, targets, and panel displayed on initial page load. These are overridden by URL parameters if present."
	learnMoreHref="./guide-for-admins/customize-page#initial_phones"
	defaultOpen
>
	<div class="ceFieldGroup">
		<span class="ceLabel">Initial Phones</span>
		<StringArrayEditor
			bind:items={config.INITIAL_PHONES}
			placeholder="Brand Model (Suffix)"
			addLabel="Add phone"
		/>
	</div>

	<div class="ceFieldGroup">
		<span class="ceLabel">Initial Targets</span>
		<StringArrayEditor
			bind:items={config.INITIAL_TARGETS}
			placeholder="Target Name"
			addLabel="Add target"
		/>
	</div>

	<div class="ceFieldGroup">
		<label class="ceLabel" for="{id}-panel">Initial Panel</label>
		<select id="{id}-panel" class="ceSelect" bind:value={config.INITIAL_PANEL}>
			{#each PANELS as p (p)}
				<option value={p}>{p}</option>
			{/each}
		</select>
	</div>
</AccordionSection>

// docs/src/components/ConfigEditor/sections/InitialSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import StringArrayEditor from '../shared/StringArrayEditor';
import styles from '../ConfigEditor.module.css';

const PANELS = ['phone', 'graph', 'equalizer', 'misc'];

export default function InitialSection() {
  const { state } = useConfigEditor();
  const { set } = useFieldSetter([]);

  return (
    <AccordionSection
      id="section-initial"
      title="Initial Settings"
      description="Phones, targets, and panel displayed on initial page load. These are overridden by URL parameters if present."
      learnMoreHref="./guide-for-admins/customize-page#initial_phones"
      defaultOpen
    >
      <div className={styles.ceFieldGroup}>
        <label className={styles.ceLabel}>Initial Phones</label>
        <StringArrayEditor
          items={state.INITIAL_PHONES}
          onChange={(items) => set('INITIAL_PHONES', items)}
          placeholder="Brand Model (Suffix)"
          addLabel="+ Add phone"
        />
      </div>

      <div className={styles.ceFieldGroup}>
        <label className={styles.ceLabel}>Initial Targets</label>
        <StringArrayEditor
          items={state.INITIAL_TARGETS}
          onChange={(items) => set('INITIAL_TARGETS', items)}
          placeholder="Target Name"
          addLabel="+ Add target"
        />
      </div>

      <div className={styles.ceFieldGroup}>
        <label className={styles.ceLabel}>Initial Panel</label>
        <select
          className={styles.ceSelect}
          value={state.INITIAL_PANEL}
          onChange={(e) => set('INITIAL_PANEL', e.target.value)}
        >
          {PANELS.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>
      </div>
    </AccordionSection>
  );
}
