// docs/src/components/tools/config-editor/sections/NormalizationSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';

	let config = $derived(configEditor.config);
	const id = $props.id();
</script>

<AccordionSection
	id="section-normalization"
	title="Normalization"
	description="Default graph normalization method. Hz normalizes to a specific frequency; Avg uses the 300-3000 Hz midrange average."
	learnMoreHref="./guide-for-admins/customize-page#normalization"
>
	<div class="ceFieldGroup">
		<span class="ceLabel">Type</span>
		<div class="ceRadioGroup">
			<label class="ceRadioLabel">
				<input
					type="radio"
					class="ceRadio"
					name="{id}-type"
					value="Hz"
					bind:group={config.NORMALIZATION.TYPE}
				/>
				Hz (specific frequency)
			</label>
			<label class="ceRadioLabel">
				<input
					type="radio"
					class="ceRadio"
					name="{id}-type"
					value="Avg"
					bind:group={config.NORMALIZATION.TYPE}
				/>
				Avg (300-3000 Hz)
			</label>
		</div>
	</div>

	{#if config.NORMALIZATION.TYPE === 'Hz'}
		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-hz">
				Frequency (Hz)
				<span class="ceLabelHint">20 - 20000</span>
			</label>
			<input
				id="{id}-hz"
				type="number"
				class="ceInput ceInputSmall"
				bind:value={config.NORMALIZATION.HZ_VALUE}
				min="20"
				max="20000"
			/>
		</div>
	{/if}
</AccordionSection>

// docs/src/components/ConfigEditor/sections/NormalizationSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import styles from '../ConfigEditor.module.css';

export default function NormalizationSection() {
  const { state } = useConfigEditor();
  const { set } = useFieldSetter(['NORMALIZATION']);

  return (
    <AccordionSection
      id="section-normalization"
      title="Normalization"
      description="Default graph normalization method. Hz normalizes to a specific frequency; Avg uses the 300-3000 Hz midrange average."
      learnMoreHref="./guide-for-admins/customize-page#normalization"
    >
      <div className={styles.ceFieldGroup}>
        <label className={styles.ceLabel}>Type</label>
        <div className={styles.ceRadioGroup}>
          <label className={styles.ceRadioLabel}>
            <input
              type="radio"
              className={styles.ceRadio}
              checked={state.NORMALIZATION.TYPE === 'Hz'}
              onChange={() => set('TYPE', 'Hz')}
            />
            Hz (specific frequency)
          </label>
          <label className={styles.ceRadioLabel}>
            <input
              type="radio"
              className={styles.ceRadio}
              checked={state.NORMALIZATION.TYPE === 'Avg'}
              onChange={() => set('TYPE', 'Avg')}
            />
            Avg (300-3000 Hz)
          </label>
        </div>
      </div>

      {state.NORMALIZATION.TYPE === 'Hz' && (
        <div className={styles.ceFieldGroup}>
          <label className={styles.ceLabel}>
            Frequency (Hz)
            <span className={styles.ceLabelHint}>20 - 20000</span>
          </label>
          <input
            type="number"
            className={`${styles.ceInput} ${styles.ceInputSmall}`}
            value={state.NORMALIZATION.HZ_VALUE}
            onChange={(e) => set('HZ_VALUE', Number(e.target.value))}
            min={20}
            max={20000}
          />
        </div>
      )}
    </AccordionSection>
  );
}
