// docs/src/components/tools/config-editor/sections/PreferenceBoundSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';
	import Checkbox from '../../shared/Checkbox.svelte';

	let config = $derived(configEditor.config);
	const id = $props.id();
</script>

<AccordionSection
	id="section-preference-bound"
	title="Preference Bound"
	description="Draws a shaded upper/lower preference bound area on the graph. Requires Bounds U.txt / Bounds D.txt in the data/ folder."
	learnMoreHref="./guide-for-admins/customize-page#preference_bound"
	optional
	bind:enabled={config.PREFERENCE_BOUND_ENABLED}
>
	<Checkbox
		bind:checked={config.PREFERENCE_BOUND.ENABLE_BOUND_ON_INITIAL_LOAD}
		label="Show bounds on initial load"
	/>

	<div class="ceFieldGroup">
		<label class="ceLabel" for="{id}-base-df">Base DF Target File</label>
		<input
			id="{id}-base-df"
			type="text"
			class="ceInput"
			bind:value={config.PREFERENCE_BOUND.BASE_DF_TARGET_FILE}
			placeholder="KEMAR DF (KB006x) Target"
		/>
	</div>

	<div class="ceCardGrid">
		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-fill">Fill Color</label>
			<input
				id="{id}-fill"
				type="text"
				class="ceInput"
				bind:value={config.PREFERENCE_BOUND.COLOR_FILL}
				placeholder="rgba(180,180,180,0.2)"
			/>
		</div>

		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-border">Border Color</label>
			<input
				id="{id}-border"
				type="text"
				class="ceInput"
				bind:value={config.PREFERENCE_BOUND.COLOR_BORDER}
				placeholder="rgba(120,120,120,0.5)"
			/>
		</div>
	</div>
</AccordionSection>

// docs/src/components/ConfigEditor/sections/PreferenceBoundSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import styles from '../ConfigEditor.module.css';

export default function PreferenceBoundSection() {
  const { state, dispatch } = useConfigEditor();
  const { set } = useFieldSetter(['PREFERENCE_BOUND']);

  return (
    <AccordionSection
      id="section-preference-bound"
      title="Preference Bound"
      description="Draws a shaded upper/lower preference bound area on the graph. Requires Bounds U.txt / Bounds D.txt in the data/ folder."
      learnMoreHref="./guide-for-admins/customize-page#preference_bound"
      optional
      enabled={state.PREFERENCE_BOUND_ENABLED}
      onToggleEnabled={(v) => dispatch({ type: 'SET_FIELD', path: ['PREFERENCE_BOUND_ENABLED'], value: v })}
    >
      <div className={styles.ceToggleRow}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={state.PREFERENCE_BOUND.ENABLE_BOUND_ON_INITIAL_LOAD}
          onChange={(e) => set('ENABLE_BOUND_ON_INITIAL_LOAD', e.target.checked)}
          id="pb-initial"
        />
        <label htmlFor="pb-initial" className={styles.ceToggleLabel}>
          Show bounds on initial load
        </label>
      </div>

      <div className={styles.ceFieldGroup}>
        <label className={styles.ceLabel}>Base DF Target File</label>
        <input
          type="text"
          className={styles.ceInput}
          value={state.PREFERENCE_BOUND.BASE_DF_TARGET_FILE}
          onChange={(e) => set('BASE_DF_TARGET_FILE', e.target.value)}
          placeholder="KEMAR DF (KB006x) Target"
        />
      </div>

      <div className={styles.ceCardGrid}>
        <div className={styles.ceFieldGroup}>
          <label className={styles.ceLabel}>Fill Color</label>
          <input
            type="text"
            className={styles.ceInput}
            value={state.PREFERENCE_BOUND.COLOR_FILL}
            onChange={(e) => set('COLOR_FILL', e.target.value)}
            placeholder="rgba(180,180,180,0.2)"
          />
        </div>

        <div className={styles.ceFieldGroup}>
          <label className={styles.ceLabel}>Border Color</label>
          <input
            type="text"
            className={styles.ceInput}
            value={state.PREFERENCE_BOUND.COLOR_BORDER}
            onChange={(e) => set('COLOR_BORDER', e.target.value)}
            placeholder="rgba(120,120,120,0.5)"
          />
        </div>
      </div>
    </AccordionSection>
  );
}
