// docs/src/components/tools/config-editor/sections/TopbarSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';
	import I18nWrapper from '../shared/I18nWrapper.svelte';
	import type { TopbarLinkForm } from '../../../../utils/configDefaults';

	let config = $derived(configEditor.config);
	const id = $props.id();
</script>

{#snippet links(items: TopbarLinkForm[], lang: string)}
	<div>
		<div class="ceArrayList">
			{#each items as link, i (i)}
				<div class="ceArrayItem">
					<input
						type="text"
						class="ceInput"
						bind:value={link.TITLE}
						placeholder="Link title"
						aria-label="Link title {i + 1} ({lang})"
						style="flex: 1;"
					/>
					<input
						type="text"
						class="ceInput"
						bind:value={link.URL}
						placeholder="https://..."
						aria-label="Link URL {i + 1} ({lang})"
						style="flex: 2;"
					/>
					<button
						type="button"
						class="ceArrayRemoveBtn"
						onclick={() => items.splice(i, 1)}
						title="Remove"
					>
						&times;
					</button>
				</div>
			{/each}
		</div>
		<button type="button" class="ceArrayAddBtn" onclick={() => items.push({ TITLE: '', URL: '' })}>
			+ Add link
		</button>
	</div>
{/snippet}

<AccordionSection
	id="section-topbar"
	title="Topbar"
	description="Header title and navigation links. Links support multilingual configuration."
	learnMoreHref="./guide-for-admins/customize-page#topbar"
>
	<div class="ceSubSection">
		<div class="ceSubSectionTitle">Title</div>
		<div class="ceCardGrid">
			<div class="ceFieldGroup">
				<label class="ceLabel" for="{id}-title-type">Type</label>
				<select id="{id}-title-type" class="ceSelect" bind:value={config.TOPBAR.TITLE.TYPE}>
					<option value="TEXT">Text</option>
					<option value="IMAGE">Image</option>
					<option value="HTML">HTML</option>
				</select>
			</div>
		</div>
		<div class="ceFieldGroup">
			<label class="ceLabel" for="{id}-title-content">Content</label>
			{#if config.TOPBAR.TITLE.TYPE === 'HTML'}
				<textarea
					id="{id}-title-content"
					class="ceTextarea"
					bind:value={config.TOPBAR.TITLE.CONTENT}
					placeholder="<h2>Site Title</h2>"></textarea>
			{:else}
				<input
					id="{id}-title-content"
					type="text"
					class="ceInput"
					bind:value={config.TOPBAR.TITLE.CONTENT}
					placeholder={config.TOPBAR.TITLE.TYPE === 'IMAGE'
						? './assets/images/logo.png'
						: 'Site Title'}
				/>
			{/if}
		</div>
	</div>

	<div class="ceFieldGroup">
		<span class="ceLabel">Link List</span>
		<I18nWrapper bind:state={config.TOPBAR.LINK_LIST} renderItems={links} />
	</div>
</AccordionSection>

// docs/src/components/ConfigEditor/sections/TopbarSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import I18nWrapper from '../shared/I18nWrapper';
import type { TopbarLinkForm } from '@site/src/utils/configDefaults';
import styles from '../ConfigEditor.module.css';

export default function TopbarSection() {
	const { state } = useConfigEditor();
	const { set } = useFieldSetter(['TOPBAR']);

	const renderLinkItems = (
		items: TopbarLinkForm[],
		onChange: (items: TopbarLinkForm[]) => void
	) => {
		const updateLink = (index: number, field: 'TITLE' | 'URL', value: string) => {
			const copy = items.map((l) => ({ ...l }));
			copy[index][field] = value;
			onChange(copy);
		};

		const removeLink = (index: number) => {
			onChange(items.filter((_, i) => i !== index));
		};

		const addLink = () => {
			onChange([...items, { TITLE: '', URL: '' }]);
		};

		return (
			<div>
				<div className={styles.ceArrayList}>
					{items.map((link, i) => (
						<div className={styles.ceArrayItem} key={i}>
							<input
								type="text"
								className={styles.ceInput}
								value={link.TITLE}
								onChange={(e) => updateLink(i, 'TITLE', e.target.value)}
								placeholder="Link title"
								style={{ flex: 1 }}
							/>
							<input
								type="text"
								className={styles.ceInput}
								value={link.URL}
								onChange={(e) => updateLink(i, 'URL', e.target.value)}
								placeholder="https://..."
								style={{ flex: 2 }}
							/>
							<button
								type="button"
								className={styles.ceArrayRemoveBtn}
								onClick={() => removeLink(i)}
								title="Remove"
							>
								&times;
							</button>
						</div>
					))}
				</div>
				<button type="button" className={styles.ceArrayAddBtn} onClick={addLink}>
					+ Add link
				</button>
			</div>
		);
	};

	return (
		<AccordionSection
			id="section-topbar"
			title="Topbar"
			description="Header title and navigation links. Links support multilingual configuration."
			learnMoreHref="./guide-for-admins/customize-page#topbar"
		>
			<div className={styles.ceSubSection}>
				<div className={styles.ceSubSectionTitle}>Title</div>
				<div className={styles.ceCardGrid}>
					<div className={styles.ceFieldGroup}>
						<label className={styles.ceLabel}>Type</label>
						<select
							className={styles.ceSelect}
							value={state.TOPBAR.TITLE.TYPE}
							onChange={(e) => set(['TITLE', 'TYPE'], e.target.value)}
						>
							<option value="TEXT">Text</option>
							<option value="IMAGE">Image</option>
							<option value="HTML">HTML</option>
						</select>
					</div>
				</div>
				<div className={styles.ceFieldGroup}>
					<label className={styles.ceLabel}>Content</label>
					{state.TOPBAR.TITLE.TYPE === 'HTML' ? (
						<textarea
							className={styles.ceTextarea}
							value={state.TOPBAR.TITLE.CONTENT}
							onChange={(e) => set(['TITLE', 'CONTENT'], e.target.value)}
							placeholder="<h2>Site Title</h2>"
						/>
					) : (
						<input
							type="text"
							className={styles.ceInput}
							value={state.TOPBAR.TITLE.CONTENT}
							onChange={(e) => set(['TITLE', 'CONTENT'], e.target.value)}
							placeholder={
								state.TOPBAR.TITLE.TYPE === 'IMAGE' ? './assets/images/logo.png' : 'Site Title'
							}
						/>
					)}
				</div>
			</div>

			<div className={styles.ceFieldGroup}>
				<label className={styles.ceLabel}>Link List</label>
				<I18nWrapper
					basePath={['TOPBAR', 'LINK_LIST']}
					state={state.TOPBAR.LINK_LIST}
					renderItems={renderLinkItems}
				/>
			</div>
		</AccordionSection>
	);
}
