// docs/src/pages/theme-generator/index.tsx
import React, { useState, useEffect, ReactNode } from 'react';
import Layout from '@theme/Layout';
import DummyGraphPage from '@site/src/components/DummyGraphPage';
import { SketchPicker, ColorResult } from 'react-color';
import Translate from '@docusaurus/Translate';
import {
	type PaletteInputs,
	type ThemePalette,
	generateFullPalette,
	oklchToHex,
	DEFAULT_INPUTS
} from '@site/src/utils/oklch';
import styles from './index.module.css';

// ── CSS export template ──────────────────────────────────────────────────────

const generateThemeCssContent = (light: ThemePalette, dark: ThemePalette): string => {
	return `/*
 * modernGraphTool — Theme Variables
 * Generated by Theme Generator
 *
 * Graph variables control D3.js SVG rendering where Tailwind classes cannot be used.
 * Base variables follow DaisyUI naming — all UI chrome is derived via opacity modifiers.
 * All variables switch automatically between light and dark mode.
 */

:root {
\t/* ── Graph ─────────────────────────────────────────────────────────── */
\t--color-graph-bg: ${light.graphBg};
\t--color-graph-watermark-opacity: ${light.graphWatermarkOpacity};
\t--color-graph-grid-major: ${light.graphGridMajor};
\t--color-graph-grid-minor: ${light.graphGridMinor};
\t--color-graph-axis-label: ${light.graphAxisLabel};
\t--color-graph-grid-text: ${light.graphGridText};
\t--color-graph-baseline: ${light.graphBaseline};

\t/* ── Base ──────────────────────────────────────────────────────────── */
\t--color-base-100: ${light.base100};
\t--color-base-200: ${light.base200};
\t--color-base-300: ${light.base300};
\t--color-base-content: ${light.baseContent};
\t--color-primary: ${light.primary};
\t--color-primary-content: ${light.primaryContent};
\t--color-secondary: ${light.secondary};
\t--color-secondary-content: ${light.secondaryContent};
\t--color-accent: ${light.accent};
\t--color-accent-content: ${light.accentContent};
\t--color-neutral: ${light.neutral};
\t--color-neutral-content: ${light.neutralContent};
\t--color-info: ${light.info};
\t--color-info-content: ${light.infoContent};
\t--color-success: ${light.success};
\t--color-success-content: ${light.successContent};
\t--color-warning: ${light.warning};
\t--color-warning-content: ${light.warningContent};
\t--color-error: ${light.error};
\t--color-error-content: ${light.errorContent};
}

.dark {
\t/* ── Graph ─────────────────────────────────────────────────────────── */
\t--color-graph-grid-major: ${dark.graphGridMajor};
\t--color-graph-grid-minor: ${dark.graphGridMinor};
\t--color-graph-axis-label: ${dark.graphAxisLabel};
\t--color-graph-grid-text: ${dark.graphGridText};
\t--color-graph-baseline: ${dark.graphBaseline};

\t/* ── Base ──────────────────────────────────────────────────────────── */
\t--color-base-100: ${dark.base100};
\t--color-base-200: ${dark.base200};
\t--color-base-300: ${dark.base300};
\t--color-base-content: ${dark.baseContent};
\t--color-primary: ${dark.primary};
\t--color-primary-content: ${dark.primaryContent};
\t--color-secondary: ${dark.secondary};
\t--color-secondary-content: ${dark.secondaryContent};
\t--color-accent: ${dark.accent};
\t--color-accent-content: ${dark.accentContent};
\t--color-neutral: ${dark.neutral};
\t--color-neutral-content: ${dark.neutralContent};
\t--color-info: ${dark.info};
\t--color-info-content: ${dark.infoContent};
\t--color-success: ${dark.success};
\t--color-success-content: ${dark.successContent};
\t--color-warning: ${dark.warning};
\t--color-warning-content: ${dark.warningContent};
\t--color-error: ${dark.error};
\t--color-error-content: ${dark.errorContent};
}
`;
};

// ── Random color generation helpers ──────────────────────────────────────────

function randomHex(): string {
	return (
		'#' +
		Math.floor(Math.random() * 16777215)
			.toString(16)
			.padStart(6, '0')
	);
}

function randomSemanticHex(
	hueCenter: number,
	hueSpread: number,
	lRange: [number, number],
	cRange: [number, number]
): string {
	const h = hueCenter + (Math.random() - 0.5) * hueSpread;
	const l = lRange[0] + Math.random() * (lRange[1] - lRange[0]);
	const c = cRange[0] + Math.random() * (cRange[1] - cRange[0]);
	return oklchToHex({ l, c, h: ((h % 360) + 360) % 360 });
}

// ── Picker presets ───────────────────────────────────────────────────────────

const PICKER_PRESETS = [
	'#2B8C5E',
	'#3A7FA8',
	'#615B73',
	'#3B82F6',
	'#8B5CF6',
	'#EC4899',
	'#EF4444',
	'#F97316',
	'#EAB308',
	'#22C55E',
	'#06B6D4',
	'#6366F1',
	'#A855F7',
	'#14B8A6',
	'#F43F5E',
	'#0EA5E9',
	'#84CC16',
	'#D946EF',
	'#FB923C',
	'#64748B'
];

// ── Component ────────────────────────────────────────────────────────────────

type SemanticColorKey =
	'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error';

export default function ThemeGenerator(): ReactNode {
	const [inputs, setInputs] = useState<PaletteInputs>(DEFAULT_INPUTS);
	const [lightTheme, setLightTheme] = useState<ThemePalette>(
		() => generateFullPalette(DEFAULT_INPUTS).light
	);
	const [darkTheme, setDarkTheme] = useState<ThemePalette>(
		() => generateFullPalette(DEFAULT_INPUTS).dark
	);
	const [activePicker, setActivePicker] = useState<string | null>(null);

	useEffect(() => {
		const timeoutId = setTimeout(() => {
			const { light, dark } = generateFullPalette(inputs);
			setLightTheme(light);
			setDarkTheme(dark);
		}, 50);
		return () => clearTimeout(timeoutId);
	}, [inputs]);

	const updateColor = (key: SemanticColorKey) => (color: ColorResult) => {
		setInputs((prev) => ({ ...prev, [key]: color.hex }));
	};

	const handleBaseHueChange = (value: number) => {
		setInputs((prev) => ({ ...prev, baseHue: Math.max(0, Math.min(360, value)) }));
	};

	const handleRandomAll = () => {
		setInputs({
			baseHue: Math.floor(Math.random() * 360),
			primary: randomHex(),
			secondary: randomHex(),
			accent: randomSemanticHex(280, 60, [0.4, 0.55], [0.01, 0.06]),
			info: randomSemanticHex(220, 40, [0.6, 0.75], [0.12, 0.2]),
			success: randomSemanticHex(130, 40, [0.65, 0.8], [0.15, 0.25]),
			warning: randomSemanticHex(75, 30, [0.7, 0.85], [0.14, 0.22]),
			error: randomSemanticHex(15, 20, [0.55, 0.7], [0.18, 0.26])
		});
	};

	const handleExport = () => {
		const css = generateThemeCssContent(lightTheme, darkTheme);
		const blob = new Blob([css], { type: 'text/css' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'theme.css';
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	};

	const togglePicker = (id: string) => {
		setActivePicker((prev) => (prev === id ? null : id));
	};

	// ── Render helpers ───────────────────────────────────────────────────────

	const renderColorPicker = (
		id: string,
		label: string,
		colorHex: string,
		onChange: (color: ColorResult) => void
	) => (
		<div className={styles.tgColorPickerWrapper} key={id}>
			<label>{label}</label>
			<button
				type="button"
				className={styles.tgColorButton}
				style={{ backgroundColor: colorHex }}
				onClick={() => togglePicker(id)}
			>
				{colorHex}
			</button>
			{activePicker === id && (
				<div className={styles.tgPickerPopover}>
					<div className={styles.tgPickerCover} onClick={() => setActivePicker(null)} />
					<SketchPicker
						className={styles.tgPickerElement}
						color={colorHex}
						onChange={onChange}
						disableAlpha={true}
						presetColors={PICKER_PRESETS}
					/>
				</div>
			)}
		</div>
	);

	return (
		<Layout title="Theme Generator" description="Theme Generator for modernGraphTool">
			<div className={styles.tgContainer}>
				<div className={styles.tgTools}>
					<h4>
						<Translate>Base Tone</Translate>
					</h4>
					<p className={styles.tgDescription}>
						<Translate>
							Controls the neutral base palette (backgrounds, text, borders). Adjust the hue to tint
							your UI surface.
						</Translate>
					</p>
					<section className={styles.tgBaseHueSection}>
						<label htmlFor="baseHueSlider">
							<Translate>Base Hue</Translate>
						</label>
						<div className={styles.tgBaseHueInputRow}>
							<input
								id="baseHueSlider"
								type="range"
								min="0"
								max="360"
								step="1"
								value={inputs.baseHue}
								className={styles.tgHueSlider}
								onChange={(e) => handleBaseHueChange(parseInt(e.target.value, 10))}
							/>
							<input
								type="number"
								min="0"
								max="360"
								step="1"
								value={inputs.baseHue}
								className={styles.tgNumberInput}
								onChange={(e) => handleBaseHueChange(parseInt(e.target.value, 10) || 0)}
							/>
						</div>
					</section>

					<h4>
						<Translate>Semantic Colors</Translate>
					</h4>
					<p className={styles.tgDescription}>
						<Translate>
							Pick colors for each role. Content (text-on-color) and dark mode variants are
							auto-generated.
						</Translate>
					</p>

					<section className={styles.tgSourceColorSection}>
						{renderColorPicker('primary', 'Primary', inputs.primary, updateColor('primary'))}
						<button
							type="button"
							className={styles.tgSourceColorRandomizerButton}
							onClick={handleRandomAll}
						>
							<Translate>Random All</Translate>
						</button>
					</section>

					{renderColorPicker('secondary', 'Secondary', inputs.secondary, updateColor('secondary'))}
					{renderColorPicker('accent', 'Accent', inputs.accent, updateColor('accent'))}

					<h4>
						<Translate>Status Colors</Translate>
					</h4>
					{renderColorPicker('info', 'Info', inputs.info, updateColor('info'))}
					{renderColorPicker('success', 'Success', inputs.success, updateColor('success'))}
					{renderColorPicker('warning', 'Warning', inputs.warning, updateColor('warning'))}
					{renderColorPicker('error', 'Error', inputs.error, updateColor('error'))}

					<button type="button" onClick={handleExport} className={styles.tgExportButton}>
						<Translate>Export theme.css</Translate>
					</button>
				</div>
				<div className={styles.tgPreview}>
					<DummyGraphPage colorMode="light" theme={lightTheme} />
					<DummyGraphPage colorMode="dark" theme={darkTheme} />
				</div>
			</div>
		</Layout>
	);
}

// docs_new/src/components/tools/theme-generator/ThemeGenerator.svelte
<script lang="ts">
	import {
		type PaletteInputs,
		type ThemePalette,
		generateFullPalette,
		oklchToHex,
		DEFAULT_INPUTS
	} from '../../../utils/oklch';
	import { createTranslator, type ToolLang } from '../../../i18n/tools';
	import ColorField from './ColorField.svelte';
	import DummyGraphPage from './DummyGraphPage.svelte';

	interface Props {
		lang: ToolLang;
	}

	let { lang }: Props = $props();
	const t = createTranslator(lang);

	// ── CSS export template ────────────────────────────────────────────────────

	const generateThemeCssContent = (light: ThemePalette, dark: ThemePalette): string => {
		return `/*
 * modernGraphTool — Theme Variables
 * Generated by Theme Generator
 *
 * Graph variables control D3.js SVG rendering where Tailwind classes cannot be used.
 * Base variables follow DaisyUI naming — all UI chrome is derived via opacity modifiers.
 * All variables switch automatically between light and dark mode.
 */

:root {
\t/* ── Graph ─────────────────────────────────────────────────────────── */
\t--color-graph-bg: ${light.graphBg};
\t--color-graph-watermark-opacity: ${light.graphWatermarkOpacity};
\t--color-graph-grid-major: ${light.graphGridMajor};
\t--color-graph-grid-minor: ${light.graphGridMinor};
\t--color-graph-axis-label: ${light.graphAxisLabel};
\t--color-graph-grid-text: ${light.graphGridText};
\t--color-graph-baseline: ${light.graphBaseline};

\t/* ── Base ──────────────────────────────────────────────────────────── */
\t--color-base-100: ${light.base100};
\t--color-base-200: ${light.base200};
\t--color-base-300: ${light.base300};
\t--color-base-content: ${light.baseContent};
\t--color-primary: ${light.primary};
\t--color-primary-content: ${light.primaryContent};
\t--color-secondary: ${light.secondary};
\t--color-secondary-content: ${light.secondaryContent};
\t--color-accent: ${light.accent};
\t--color-accent-content: ${light.accentContent};
\t--color-neutral: ${light.neutral};
\t--color-neutral-content: ${light.neutralContent};
\t--color-info: ${light.info};
\t--color-info-content: ${light.infoContent};
\t--color-success: ${light.success};
\t--color-success-content: ${light.successContent};
\t--color-warning: ${light.warning};
\t--color-warning-content: ${light.warningContent};
\t--color-error: ${light.error};
\t--color-error-content: ${light.errorContent};
}

.dark {
\t/* ── Graph ─────────────────────────────────────────────────────────── */
\t--color-graph-grid-major: ${dark.graphGridMajor};
\t--color-graph-grid-minor: ${dark.graphGridMinor};
\t--color-graph-axis-label: ${dark.graphAxisLabel};
\t--color-graph-grid-text: ${dark.graphGridText};
\t--color-graph-baseline: ${dark.graphBaseline};

\t/* ── Base ──────────────────────────────────────────────────────────── */
\t--color-base-100: ${dark.base100};
\t--color-base-200: ${dark.base200};
\t--color-base-300: ${dark.base300};
\t--color-base-content: ${dark.baseContent};
\t--color-primary: ${dark.primary};
\t--color-primary-content: ${dark.primaryContent};
\t--color-secondary: ${dark.secondary};
\t--color-secondary-content: ${dark.secondaryContent};
\t--color-accent: ${dark.accent};
\t--color-accent-content: ${dark.accentContent};
\t--color-neutral: ${dark.neutral};
\t--color-neutral-content: ${dark.neutralContent};
\t--color-info: ${dark.info};
\t--color-info-content: ${dark.infoContent};
\t--color-success: ${dark.success};
\t--color-success-content: ${dark.successContent};
\t--color-warning: ${dark.warning};
\t--color-warning-content: ${dark.warningContent};
\t--color-error: ${dark.error};
\t--color-error-content: ${dark.errorContent};
}
`;
	};

	// ── Random color generation helpers ────────────────────────────────────────

	function randomHex(): string {
		return (
			'#' +
			Math.floor(Math.random() * 16777215)
				.toString(16)
				.padStart(6, '0')
		);
	}

	function randomSemanticHex(
		hueCenter: number,
		hueSpread: number,
		lRange: [number, number],
		cRange: [number, number]
	): string {
		const h = hueCenter + (Math.random() - 0.5) * hueSpread;
		const l = lRange[0] + Math.random() * (lRange[1] - lRange[0]);
		const c = cRange[0] + Math.random() * (cRange[1] - cRange[0]);
		return oklchToHex({ l, c, h: ((h % 360) + 360) % 360 });
	}

	// ── State ──────────────────────────────────────────────────────────────────

	let inputs = $state<PaletteInputs>({ ...DEFAULT_INPUTS });

	/*
	 * The React original debounced this behind a 50ms `setTimeout` because every
	 * `SketchPicker` drag fired a state update that re-rendered both previews.
	 * `generateFullPalette` is pure arithmetic over ~20 colours, and Svelte
	 * updates only the inline styles that actually changed, so the debounce —
	 * and the visible lag it introduced on every edit — is not needed.
	 */
	let palette = $derived(generateFullPalette(inputs));

	const semanticFields = [
		{ key: 'primary', label: 'Primary' },
		{ key: 'secondary', label: 'Secondary' },
		{ key: 'accent', label: 'Accent' }
	] as const;

	const statusFields = [
		{ key: 'info', label: 'Info' },
		{ key: 'success', label: 'Success' },
		{ key: 'warning', label: 'Warning' },
		{ key: 'error', label: 'Error' }
	] as const;

	function handleRandomAll() {
		inputs = {
			baseHue: Math.floor(Math.random() * 360),
			primary: randomHex(),
			secondary: randomHex(),
			accent: randomSemanticHex(280, 60, [0.4, 0.55], [0.01, 0.06]),
			info: randomSemanticHex(220, 40, [0.6, 0.75], [0.12, 0.2]),
			success: randomSemanticHex(130, 40, [0.65, 0.8], [0.15, 0.25]),
			warning: randomSemanticHex(75, 30, [0.7, 0.85], [0.14, 0.22]),
			error: randomSemanticHex(15, 20, [0.55, 0.7], [0.18, 0.26])
		};
	}

	function handleBaseHueChange(raw: number) {
		if (Number.isNaN(raw)) return;
		inputs.baseHue = Math.max(0, Math.min(360, raw));
	}

	function handleExport() {
		const css = generateThemeCssContent(palette.light, palette.dark);
		const blob = new Blob([css], { type: 'text/css' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'theme.css';
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}
</script>

<div class="tgContainer">
	<div class="tgTools">
		<h4>{t('Base Tone')}</h4>
		<p class="tgDescription">
			{t(
				'Controls the neutral base palette (backgrounds, text, borders). Adjust the hue to tint your UI surface.'
			)}
		</p>
		<section class="tgBaseHueSection">
			<label for="baseHueSlider">{t('Base Hue')}</label>
			<div class="tgBaseHueInputRow">
				<input
					id="baseHueSlider"
					type="range"
					min="0"
					max="360"
					step="1"
					class="tgHueSlider"
					value={inputs.baseHue}
					oninput={(e) => handleBaseHueChange(e.currentTarget.valueAsNumber)}
				/>
				<input
					type="number"
					aria-label={t('Base Hue')}
					min="0"
					max="360"
					step="1"
					class="tgNumberInput"
					value={inputs.baseHue}
					oninput={(e) => handleBaseHueChange(e.currentTarget.valueAsNumber)}
				/>
			</div>
		</section>

		<h4>{t('Semantic Colors')}</h4>
		<p class="tgDescription">
			{t(
				'Pick colors for each role. Content (text-on-color) and dark mode variants are auto-generated.'
			)}
		</p>

		<section class="tgSourceColorSection">
			<ColorField label="Primary" bind:value={inputs.primary} />
			<button type="button" class="tgSourceColorRandomizerButton" onclick={handleRandomAll}>
				{t('Random All')}
			</button>
		</section>

		{#each semanticFields.slice(1) as { key, label } (key)}
			<ColorField {label} bind:value={inputs[key]} />
		{/each}

		<h4>{t('Status Colors')}</h4>
		{#each statusFields as { key, label } (key)}
			<ColorField {label} bind:value={inputs[key]} />
		{/each}

		<button type="button" class="tgExportButton" onclick={handleExport}>
			{t('Export theme.css')}
		</button>
	</div>
	<div class="tgPreview">
		<DummyGraphPage colorMode="light" theme={palette.light} />
		<DummyGraphPage colorMode="dark" theme={palette.dark} />
	</div>
</div>

<style>
	/*
	 * Carried over from the Docusaurus `page-theme-generator.module.css`, minus
	 * the `.tgPicker*` rules that only existed to position react-color's
	 * popover. The `--ifm-*` variables resolve through `styles/infima-compat.css`.
	 */
	.tgContainer {
		display: flex;
		gap: 20px;
		padding: 20px;
		flex-wrap: wrap;
	}

	.tgTools {
		flex: 1;
		min-width: 300px;
		padding: 15px;
		border: 1px solid var(--ifm-color-emphasis-300);
		border-radius: 8px;
		background-color: var(--ifm-background-color);
	}

	.tgTools h4 {
		margin-bottom: 10px;
		border-bottom: 1px solid var(--ifm-color-emphasis-200);
		padding-bottom: 5px;
	}

	.tgDescription {
		font-size: 0.85rem;
		color: var(--ifm-color-emphasis-600);
		margin-bottom: 1rem;
	}

	/*
	 * The randomiser sits on the baseline of Primary's field, which is now three
	 * rows tall rather than two, so it aligns to the bottom instead of being
	 * nudged up by a fixed margin the way it was against the old swatch button.
	 */
	.tgSourceColorSection {
		display: flex;
		flex-direction: row;
		justify-content: center;
		align-items: flex-end;
		width: 100%;
		gap: 10px;
	}

	.tgSourceColorRandomizerButton {
		padding: 8px 12px;
		border: 1px solid var(--ifm-color-emphasis-300);
		border-radius: 4px;
		background-color: var(--ifm-color-emphasis-100);
		color: var(--ifm-font-color-base);
		cursor: pointer;
		margin-bottom: 15px;
		min-height: 38px;
		white-space: nowrap;
	}

	.tgPreview {
		flex: 2;
		min-width: 400px;
		display: flex;
		flex-direction: column;
		gap: 20px;
	}

	/* ── Base hue controls ───────────────────────────────────────────────────── */

	.tgBaseHueSection {
		margin-bottom: 15px;
		display: flex;
		flex-direction: column;
		width: 100%;
	}

	.tgBaseHueSection label {
		font-weight: bold;
		font-size: 0.9rem;
		margin-bottom: 4px;
	}

	.tgBaseHueInputRow {
		display: flex;
		flex-direction: row;
		align-items: center;
		width: 100%;
		gap: 10px;
	}

	.tgBaseHueInputRow input:first-child {
		width: 100%;
	}

	.tgHueSlider {
		-webkit-appearance: none;
		appearance: none;
		width: 100%;
		height: 8px;
		border-radius: 4px;
		outline: none;
		background: linear-gradient(
			to right,
			hsl(0, 70%, 60%),
			hsl(60, 70%, 60%),
			hsl(120, 70%, 60%),
			hsl(180, 70%, 60%),
			hsl(240, 70%, 60%),
			hsl(300, 70%, 60%),
			hsl(360, 70%, 60%)
		);
	}

	.tgHueSlider::-webkit-slider-thumb {
		-webkit-appearance: none;
		appearance: none;
		width: 16px;
		height: 16px;
		border-radius: 50%;
		background: white;
		border: 2px solid var(--ifm-color-emphasis-400);
		cursor: pointer;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
	}

	.tgHueSlider::-moz-range-thumb {
		width: 16px;
		height: 16px;
		border-radius: 50%;
		background: white;
		border: 2px solid var(--ifm-color-emphasis-400);
		cursor: pointer;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
	}

	.tgNumberInput {
		width: 70px;
		padding: 8px 12px;
		border: 1px solid var(--ifm-color-emphasis-300);
		border-radius: 4px;
		background-color: var(--ifm-color-emphasis-100);
		color: var(--ifm-font-color-base);
	}

	/* ── Export button ───────────────────────────────────────────────────────── */

	/*
	 * `bg-accent` / `text-invert` is Starlight's own solid-button pair and is
	 * legible in both themes. The Infima original hardcoded white on
	 * `primary-dark`, which Starlight's light-mode accent is too pale to carry.
	 */
	.tgExportButton {
		margin-top: 1rem;
		padding: 0.5rem 1rem;
		border: 1px solid var(--sl-color-bg-accent);
		background-color: var(--sl-color-bg-accent);
		color: var(--sl-color-text-invert);
		border-radius: 4px;
		width: 100%;
		height: 38px;
		cursor: pointer;
		font-weight: bold;
	}

	.tgExportButton:hover {
		filter: brightness(1.1);
	}
</style>
