// docs/src/components/tools/config-editor/ImportPanel.svelte
<script lang="ts">
	import { Tabs } from 'bits-ui';
	import Icon from '../shared/Icon.svelte';
	import { configEditor } from './config-store.svelte';
	import {
		parseV2Config,
		parseV1Config,
		parseV1Extensions,
		parseCrinGraphConfig,
		convertV1ToV2,
		convertCrinGraphToV2,
		configToFormState
	} from '../../../utils/configConverter';

	type ImportTab = 'v2' | 'v1' | 'crin';

	const TABS: Array<{ id: ImportTab; label: string; placeholder: string }> = [
		{ id: 'v2', label: 'Import v2', placeholder: 'Paste your v2 config.js content here...' },
		{ id: 'v1', label: 'Convert v1', placeholder: 'Paste your v1 config.js content here...' },
		{
			id: 'crin',
			label: 'Convert CrinGraph',
			placeholder: 'Paste your CrinGraph config.js content here...'
		}
	];

	let activeTab = $state<ImportTab>('v2');
	let input = $state('');
	let v1Extensions = $state('');
	let error = $state<string | null>(null);
	let warnings = $state<string[]>([]);
	let success = $state<string | null>(null);
	let fileInput = $state<HTMLInputElement | null>(null);

	let activePlaceholder = $derived(TABS.find((t) => t.id === activeTab)!.placeholder);

	function clearMessages() {
		error = null;
		warnings = [];
		success = null;
	}

	/*
	 * Tabs.Root drives `activeTab` through the binding, so this only has the
	 * side effect left to do. It takes a `string` because that is what bits-ui
	 * hands back; the value can only ever be one of the three trigger values.
	 */
	function selectTab(tab: string) {
		activeTab = tab as ImportTab;
		clearMessages();
	}

	function loadDefaults() {
		clearMessages();
		configEditor.reset();
		input = '';
		v1Extensions = '';
		success = 'Loaded default configuration.';
	}

	function handleImport() {
		clearMessages();
		if (!input.trim()) {
			const kind = activeTab === 'v2' ? 'v2' : activeTab === 'v1' ? 'v1' : 'CrinGraph';
			error = `Please paste your ${kind} config.js content.`;
			return;
		}
		try {
			if (activeTab === 'v2') {
				configEditor.load(configToFormState(parseV2Config(input)));
				success = 'Config imported successfully. Edit the fields below and export when ready.';
				return;
			}

			// Both conversions round-trip through the emitted v2 string rather than
			// building form state directly, so the import path exercises the same
			// parser an operator's own file would.
			const result =
				activeTab === 'v1'
					? convertV1ToV2(
							parseV1Config(input),
							v1Extensions.trim() ? parseV1Extensions(v1Extensions) : null
						)
					: convertCrinGraphToV2(parseCrinGraphConfig(input));

			warnings = result.warnings;
			configEditor.load(configToFormState(parseV2Config(result.output)));
			success =
				activeTab === 'v1'
					? 'v1 config converted and imported. Review the settings below.'
					: 'CrinGraph config converted and imported. Review the settings below.';
		} catch (e) {
			error = e instanceof Error ? e.message : String(e);
		}
	}

	function handleFileUpload(e: Event & { currentTarget: HTMLInputElement }) {
		const file = e.currentTarget.files?.[0];
		if (!file) return;
		const reader = new FileReader();
		reader.onload = () => {
			input = reader.result as string;
		};
		reader.readAsText(file);
		// Reset file input so re-uploading the same file triggers change
		if (fileInput) fileInput.value = '';
	}
</script>

<!--
	bits-ui Tabs replaces three hand-rolled <button>s. The visible difference is
	small; the behavioural one is not — the tab strip is now a single tab stop
	with Left/Right arrow navigation, and each panel is a real `tabpanel` bound
	to its trigger. The panel holds only the textareas: the action row and the
	result messages are shared across all three tabs, so duplicating them into
	every panel would just mean three file inputs racing for one `bind:this`.
-->
<Tabs.Root class="ceImportPanel" value={activeTab} onValueChange={selectTab}>
	<Tabs.List class="ceTabs">
		{#each TABS as tab (tab.id)}
			<Tabs.Trigger class="ceTab" value={tab.id}>{tab.label}</Tabs.Trigger>
		{/each}
	</Tabs.List>

	{#each TABS as tab (tab.id)}
		<Tabs.Content class="ceTabContent" value={tab.id}>
			<textarea
				class="ceImportTextarea"
				placeholder={activePlaceholder}
				aria-label={activePlaceholder}
				bind:value={input}
				spellcheck="false"></textarea>

			{#if tab.id === 'v1'}
				<textarea
					class="ceImportTextarea ceImportTextareaShort"
					placeholder="Paste your v1 extensions.config.js content here (optional)..."
					aria-label="v1 extensions.config.js content"
					bind:value={v1Extensions}
					spellcheck="false"></textarea>
			{/if}
		</Tabs.Content>
	{/each}

	<div class="ceImportActions">
		<button type="button" class="ceBtn ceBtnPrimary" onclick={handleImport}>
			<Icon name="download" />
			{activeTab === 'v2' ? 'Import' : 'Convert & Import'}
		</button>
		<label class="ceImportFileLabel">
			<Icon name="upload" />
			Upload file
			<input
				bind:this={fileInput}
				type="file"
				accept=".js,.txt"
				class="ceImportFileInput"
				onchange={handleFileUpload}
			/>
		</label>
		<button type="button" class="ceBtn" onclick={loadDefaults}>Start Fresh</button>
	</div>

	{#if error}
		<p class="ceError">{error}</p>
	{/if}
	{#if warnings.length > 0}
		<div class="ceWarnings">
			<strong>Warnings:</strong>
			<ul>
				{#each warnings as w, i (i)}
					<li>{w}</li>
				{/each}
			</ul>
		</div>
	{/if}
	{#if success}
		<p class="ceSuccess">{success}</p>
	{/if}
</Tabs.Root>

// docs/src/components/ConfigEditor/ImportPanel.tsx
import React, { useState, useRef, type ReactNode } from 'react';
import { useConfigEditor } from './ConfigEditorContext';
import {
  parseV2Config,
  parseV1Config,
  parseV1Extensions,
  parseCrinGraphConfig,
  convertV1ToV2,
  convertCrinGraphToV2,
  configToFormState,
} from '@site/src/utils/configConverter';
import { createDefaultConfig } from '@site/src/utils/configDefaults';
import styles from './ConfigEditor.module.css';

type ImportTab = 'v2' | 'v1' | 'crin';

export default function ImportPanel(): ReactNode {
  const { dispatch } = useConfigEditor();
  const [activeTab, setActiveTab] = useState<ImportTab>('v2');
  const [input, setInput] = useState('');
  const [v1Extensions, setV1Extensions] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);
  const [success, setSuccess] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  const clearMessages = () => {
    setError(null);
    setWarnings([]);
    setSuccess(null);
  };

  const loadDefaults = () => {
    clearMessages();
    dispatch({ type: 'RESET_DEFAULTS' });
    setInput('');
    setV1Extensions('');
    setSuccess('Loaded default configuration.');
  };

  const importV2 = () => {
    clearMessages();
    if (!input.trim()) {
      setError('Please paste your v2 config.js content.');
      return;
    }
    try {
      const raw = parseV2Config(input);
      const formState = configToFormState(raw);
      dispatch({ type: 'LOAD_CONFIG', config: formState });
      setSuccess('Config imported successfully. Edit the fields below and export when ready.');
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  const importV1 = () => {
    clearMessages();
    if (!input.trim()) {
      setError('Please paste your v1 config.js content.');
      return;
    }
    try {
      const config = parseV1Config(input);
      let extensions: any[] | null = null;
      if (v1Extensions.trim()) {
        extensions = parseV1Extensions(v1Extensions);
      }
      const result = convertV1ToV2(config, extensions);
      setWarnings(result.warnings);
      // Parse the generated v2 string back into form state
      const raw = parseV2Config(result.output);
      const formState = configToFormState(raw);
      dispatch({ type: 'LOAD_CONFIG', config: formState });
      setSuccess('v1 config converted and imported. Review the settings below.');
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  const importCrin = () => {
    clearMessages();
    if (!input.trim()) {
      setError('Please paste your CrinGraph config.js content.');
      return;
    }
    try {
      const config = parseCrinGraphConfig(input);
      const result = convertCrinGraphToV2(config);
      setWarnings(result.warnings);
      const raw = parseV2Config(result.output);
      const formState = configToFormState(raw);
      dispatch({ type: 'LOAD_CONFIG', config: formState });
      setSuccess('CrinGraph config converted and imported. Review the settings below.');
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  const handleImport = () => {
    switch (activeTab) {
      case 'v2': return importV2();
      case 'v1': return importV1();
      case 'crin': return importCrin();
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      setInput(reader.result as string);
    };
    reader.readAsText(file);
    // Reset file input so re-uploading the same file triggers change
    if (fileRef.current) fileRef.current.value = '';
  };

  return (
    <div className={styles.ceImportPanel}>
      <div className={styles.ceImportTabs}>
        <button
          type="button"
          className={`${styles.ceImportTab} ${activeTab === 'v2' ? styles.ceImportTabActive : ''}`}
          onClick={() => { setActiveTab('v2'); clearMessages(); }}
        >
          Import v2
        </button>
        <button
          type="button"
          className={`${styles.ceImportTab} ${activeTab === 'v1' ? styles.ceImportTabActive : ''}`}
          onClick={() => { setActiveTab('v1'); clearMessages(); }}
        >
          Convert v1
        </button>
        <button
          type="button"
          className={`${styles.ceImportTab} ${activeTab === 'crin' ? styles.ceImportTabActive : ''}`}
          onClick={() => { setActiveTab('crin'); clearMessages(); }}
        >
          Convert CrinGraph
        </button>
      </div>

      <div className={styles.ceImportContent}>
        <textarea
          className={styles.ceImportTextarea}
          placeholder={
            activeTab === 'v2'
              ? 'Paste your v2 config.js content here...'
              : activeTab === 'v1'
              ? 'Paste your v1 config.js content here...'
              : 'Paste your CrinGraph config.js content here...'
          }
          value={input}
          onChange={(e) => setInput(e.target.value)}
          spellCheck={false}
        />

        {activeTab === 'v1' && (
          <textarea
            className={styles.ceImportTextarea}
            placeholder="Paste your v1 extensions.config.js content here (optional)..."
            value={v1Extensions}
            onChange={(e) => setV1Extensions(e.target.value)}
            spellCheck={false}
            style={{ minHeight: '120px' }}
          />
        )}

        <div className={styles.ceImportActions}>
          <button type="button" className={`${styles.ceBtn} ${styles.ceBtnPrimary}`} onClick={handleImport}>
            {activeTab === 'v2' ? 'Import' : 'Convert & Import'}
          </button>
          <label className={styles.ceImportFileLabel}>
            Upload file
            <input
              ref={fileRef}
              type="file"
              accept=".js,.txt"
              className={styles.ceImportFileInput}
              onChange={handleFileUpload}
            />
          </label>
          <button type="button" className={styles.ceBtn} onClick={loadDefaults}>
            Start Fresh
          </button>
        </div>

        {error && <div className={styles.ceError}>{error}</div>}
        {warnings.length > 0 && (
          <div className={styles.ceWarnings}>
            <strong>Warnings:</strong>
            <ul>
              {warnings.map((w, i) => <li key={i}>{w}</li>)}
            </ul>
          </div>
        )}
        {success && <div className={styles.ceSuccess}>{success}</div>}
      </div>
    </div>
  );
}
