// docs/src/components/tools/phone-book-editor/BrandList.svelte
<script lang="ts">
	import { createEmptyBrand } from '../../../utils/phoneBookConverter';
	import { phoneBook, moveBy } from './phone-book-store.svelte';
	import Icon from '../shared/Icon.svelte';

	interface Props {
		selectedBrandId: string | null;
		onSelect: (brandId: string) => void;
	}

	let { selectedBrandId, onSelect }: Props = $props();

	let brands = $derived(phoneBook.book);

	function handleAdd() {
		const brand = createEmptyBrand();
		brands.push(brand);
		onSelect(brand.id);
	}
</script>

<!--
	Left-column brand picker. One-at-a-time selection; only the selected
	brand's workspace is rendered on the right, which scales to 100+ brands.
-->
<aside class="pbPicker">
	<div class="pbPickerHeader">
		<span class="pbPickerTitle">
			Brands <span class="pbPickerCount">({brands.length})</span>
		</span>
		<button
			type="button"
			class="pbIconBtn"
			onclick={() => phoneBook.sortBrandsAlpha()}
			aria-label="Sort brands A to Z"
			disabled={brands.length < 2}
		>
			<Icon name="sort" />
		</button>
	</div>

	{#if brands.length === 0}
		<p class="pbEmptyPicker">No brands yet.</p>
	{:else}
		<ul class="pbPickerList">
			{#each brands as brand, i (brand.id)}
				{@const label = [brand.name || '(unnamed)', brand.suffix].filter(Boolean).join(' ')}
				<li>
					<!--
						The row is a <div>, not a <button>: it carries the move-up/down
						buttons, and a button cannot contain another button. Selection is a
						real <button> on the label instead, so it stays keyboard-reachable
						without the React version's role/tabindex on a clickable parent.
					-->
					<div class="pbBrandButton" class:pbBrandButtonSelected={brand.id === selectedBrandId}>
						<button
							type="button"
							class="pbBrandButtonSelect"
							onclick={() => onSelect(brand.id)}
							aria-current={brand.id === selectedBrandId}
						>
							<span class="pbBrandButtonLabel">{label}</span>
							<span class="pbBrandButtonCount">{brand.phones.length}</span>
						</button>
						<span class="pbBrandButtonActions">
							<button
								type="button"
								class="pbIconBtnMini"
								onclick={() => moveBy(brands, brand, 'up')}
								disabled={i === 0}
								aria-label="Move {label} up"
							>
								<Icon name="arrow-up" />
							</button>
							<button
								type="button"
								class="pbIconBtnMini"
								onclick={() => moveBy(brands, brand, 'down')}
								disabled={i === brands.length - 1}
								aria-label="Move {label} down"
							>
								<Icon name="arrow-down" />
							</button>
						</span>
					</div>
				</li>
			{/each}
		</ul>
	{/if}

	<button type="button" class="pbBrandAddBtn" onclick={handleAdd}>
		<Icon name="plus" />
		Add brand
	</button>
</aside>

// docs/src/components/PhoneBookEditor/BrandList.tsx
import React, { type ReactNode } from 'react';
import { usePhoneBookEditor } from './PhoneBookEditorContext';
import { createEmptyBrand } from '@site/src/utils/phoneBookConverter';
import styles from './PhoneBookEditor.module.css';

interface BrandListProps {
  selectedBrandId: string | null;
  onSelect: (brandId: string) => void;
}

/**
 * Left-column brand picker. One-at-a-time selection; only the selected
 * brand's workspace is rendered on the right, which scales to 100+ brands.
 */
export default function BrandList({ selectedBrandId, onSelect }: BrandListProps): ReactNode {
  const { state, dispatch } = usePhoneBookEditor();

  const handleAdd = () => {
    const brand = createEmptyBrand();
    dispatch({ type: 'ADD_BRAND', brand });
    onSelect(brand.id);
  };

  const handleSort = () => dispatch({ type: 'SORT_BRANDS_ALPHA' });

  return (
    <aside className={styles.pbPicker}>
      <div className={styles.pbPickerHeader}>
        <span className={styles.pbPickerTitle}>
          Brands <span className={styles.pbPickerCount}>({state.length})</span>
        </span>
        <button
          type="button"
          className={styles.pbIconBtn}
          onClick={handleSort}
          title="Sort brands A → Z"
          disabled={state.length < 2}
        >
          A↓
        </button>
      </div>

      {state.length === 0 ? (
        <div className={styles.pbEmptyPicker}>
          No brands yet.
        </div>
      ) : (
        <ul className={styles.pbPickerList}>
          {state.map((brand, i) => {
            const isSelected = brand.id === selectedBrandId;
            const label = [brand.name || '(unnamed)', brand.suffix].filter(Boolean).join(' ');
            return (
              <li key={brand.id}>
                <button
                  type="button"
                  className={`${styles.pbBrandButton} ${isSelected ? styles.pbBrandButtonSelected : ''}`}
                  onClick={() => onSelect(brand.id)}
                >
                  <span className={styles.pbBrandButtonLabel}>{label}</span>
                  <span className={styles.pbBrandButtonCount}>{brand.phones.length}</span>
                  <span
                    className={styles.pbBrandButtonActions}
                    onClick={(e) => e.stopPropagation()}
                  >
                    <button
                      type="button"
                      className={styles.pbIconBtnMini}
                      onClick={() =>
                        dispatch({ type: 'MOVE_BRAND', brandId: brand.id, direction: 'up' })
                      }
                      disabled={i === 0}
                      title="Move up"
                    >
                      ↑
                    </button>
                    <button
                      type="button"
                      className={styles.pbIconBtnMini}
                      onClick={() =>
                        dispatch({ type: 'MOVE_BRAND', brandId: brand.id, direction: 'down' })
                      }
                      disabled={i === state.length - 1}
                      title="Move down"
                    >
                      ↓
                    </button>
                  </span>
                </button>
              </li>
            );
          })}
        </ul>
      )}

      <button type="button" className={styles.pbBrandAddBtn} onClick={handleAdd}>
        + Add brand
      </button>
    </aside>
  );
}
