// docs/src/components/tools/phone-book-editor/PhoneBookEditor.svelte
<script lang="ts">
	// The phone_book editor reuses the config editor's form controls (.ceInput,
	// .ceBtn, .ceLabel, …), so both stylesheets load here.
	import '../config-editor/config-editor.css';
	import './phone-book-editor.css';

	import { phoneBook } from './phone-book-store.svelte';
	import ImportPanel from './ImportPanel.svelte';
	import ExportBar from './ExportBar.svelte';
	import BrandList from './BrandList.svelte';
	import BrandEditor from './BrandEditor.svelte';

	let selectedBrandId = $state<string | null>(null);

	/*
	 * Keep the selection valid: default to the first brand, and recover when the
	 * selected one is deleted or the whole phone book is replaced by an import.
	 * `$derived` rather than the React version's `useEffect` + `setState`, so
	 * there is no render where the selection points at a brand that is gone.
	 */
	let selectedBrand = $derived(
		phoneBook.book.find((b) => b.id === selectedBrandId) ?? phoneBook.book[0] ?? null
	);
</script>

<div class="ceContainer">
	<ImportPanel />
	<div class="pbLayout">
		<BrandList
			selectedBrandId={selectedBrand?.id ?? null}
			onSelect={(id) => (selectedBrandId = id)}
		/>
		<!--
			Keyed on the brand so each brand gets its own expand/collapse state
			without an effect to reset it.
		-->
		{#key selectedBrand?.id}
			<BrandEditor brand={selectedBrand} onBrandDeleted={() => (selectedBrandId = null)} />
		{/key}
	</div>
	<ExportBar />
</div>

// docs/src/components/PhoneBookEditor/PhoneBookEditor.tsx
import React, { useEffect, useState, type ReactNode } from 'react';
import {
  PhoneBookEditorProvider,
  usePhoneBookEditor,
} from './PhoneBookEditorContext';
import ImportPanel from './ImportPanel';
import ExportBar from './ExportBar';
import BrandList from './BrandList';
import BrandEditor from './BrandEditor';
import ceStyles from '../ConfigEditor/ConfigEditor.module.css';
import styles from './PhoneBookEditor.module.css';

function PhoneBookEditorInner(): ReactNode {
  const { state } = usePhoneBookEditor();
  const [selectedBrandId, setSelectedBrandId] = useState<string | null>(null);

  // Keep the selected brand in sync with the underlying state: default to the
  // first brand, and recover gracefully when the selected brand is deleted or
  // the whole phone book is reloaded.
  useEffect(() => {
    if (state.length === 0) {
      if (selectedBrandId !== null) setSelectedBrandId(null);
      return;
    }
    if (!selectedBrandId || !state.some((b) => b.id === selectedBrandId)) {
      setSelectedBrandId(state[0].id);
    }
  }, [state, selectedBrandId]);

  const selectedBrand = state.find((b) => b.id === selectedBrandId) ?? null;

  const handleBrandDeleted = () => {
    // The effect above will pick the next available brand on the next render.
    setSelectedBrandId(null);
  };

  return (
    <div className={ceStyles.ceContainer}>
      <ImportPanel />
      <div className={styles.pbLayout}>
        <BrandList selectedBrandId={selectedBrandId} onSelect={setSelectedBrandId} />
        <BrandEditor brand={selectedBrand} onBrandDeleted={handleBrandDeleted} />
      </div>
      <ExportBar />
    </div>
  );
}

export default function PhoneBookEditor(): ReactNode {
  return (
    <PhoneBookEditorProvider>
      <PhoneBookEditorInner />
    </PhoneBookEditorProvider>
  );
}
