// docs/src/components/ConfigEditor/shared/I18nWrapper.tsx
import React, { useState, type ReactNode } from 'react';
import { useConfigEditor } from '../ConfigEditorContext';
import type { I18nArrayFormState } from '@site/src/utils/configDefaults';
import styles from '../ConfigEditor.module.css';

interface I18nWrapperProps<T> {
  /** Path in state to the I18nArrayFormState field */
  basePath: string[];
  state: I18nArrayFormState<T>;
  /** Render the item editor for a given language's items */
  renderItems: (items: T[], onChange: (items: T[]) => void, lang: string) => ReactNode;
}

export default function I18nWrapper<T>({
  basePath,
  state,
  renderItems,
}: I18nWrapperProps<T>) {
  const { dispatch, state: configState } = useConfigEditor();
  const [activeLang, setActiveLang] = useState<string | null>(null);

  const languageList = configState.LANGUAGE.LANGUAGE_LIST;

  const setUseI18n = (enabled: boolean) => {
    dispatch({ type: 'SET_FIELD', path: [...basePath, 'useI18n'], value: enabled });
  };

  const setItems = (items: T[]) => {
    dispatch({ type: 'SET_FIELD', path: [...basePath, 'items'], value: items });
  };

  const setLangItems = (lang: string, items: T[]) => {
    dispatch({
      type: 'SET_FIELD',
      path: [...basePath, 'i18n', lang],
      value: items,
    });
  };

  if (!state.useI18n) {
    return (
      <div>
        <div className={styles.ceI18nToggle}>
          <input
            type="checkbox"
            className={styles.ceCheckbox}
            checked={false}
            onChange={() => setUseI18n(true)}
            id={`i18n-toggle-${basePath.join('-')}`}
          />
          <label htmlFor={`i18n-toggle-${basePath.join('-')}`} className={styles.ceToggleLabel}>
            Enable multilingual support
          </label>
        </div>
        {renderItems(state.items, setItems, 'default')}
      </div>
    );
  }

  // i18n mode: show tabs for default + each language
  const langs = languageList.map(([code]) => code).filter((c) => c !== 'en');
  const currentLang = activeLang ?? 'default';

  return (
    <div>
      <div className={styles.ceI18nToggle}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={true}
          onChange={() => setUseI18n(false)}
          id={`i18n-toggle-${basePath.join('-')}`}
        />
        <label htmlFor={`i18n-toggle-${basePath.join('-')}`} className={styles.ceToggleLabel}>
          Enable multilingual support
        </label>
      </div>
      <div className={styles.ceI18nTabs}>
        <button
          type="button"
          className={`${styles.ceI18nTab} ${currentLang === 'default' ? styles.ceI18nTabActive : ''}`}
          onClick={() => setActiveLang(null)}
        >
          Default (EN)
        </button>
        {langs.map((code) => {
          const label = languageList.find(([c]) => c === code)?.[1] ?? code;
          return (
            <button
              key={code}
              type="button"
              className={`${styles.ceI18nTab} ${currentLang === code ? styles.ceI18nTabActive : ''}`}
              onClick={() => setActiveLang(code)}
            >
              {label}
            </button>
          );
        })}
      </div>
      {currentLang === 'default'
        ? renderItems(state.items, setItems, 'default')
        : renderItems(
            state.i18n[currentLang] ?? [],
            (items) => setLangItems(currentLang, items),
            currentLang,
          )}
    </div>
  );
}

// docs/src/components/tools/config-editor/shared/I18nWrapper.svelte
<script lang="ts" generics="T">
	import type { Snippet } from 'svelte';
	import type { I18nArrayFormState } from '../../../../utils/configDefaults';
	import { configEditor } from '../config-store.svelte';

	interface Props {
		state: I18nArrayFormState<T>;
		/** Renders the item editor for one language's items, which it may mutate. */
		renderItems: Snippet<[T[], string]>;
	}

	let { state = $bindable(), renderItems }: Props = $props();

	let activeLang = $state<string | null>(null);
	const toggleId = $props.id();

	let languageList = $derived(configEditor.config.LANGUAGE.LANGUAGE_LIST);
	let langs = $derived(languageList.map(([code]) => code).filter((c) => c !== 'en'));
	let currentLang = $derived(activeLang ?? 'default');

	/*
	 * The React version read `state.i18n[lang] ?? []` and handed the fallback to
	 * the renderer, so edits to a language that had no entry yet were written to
	 * a throwaway array and lost. Mutating in place means the slot has to exist
	 * first, which also fixes that.
	 */
	function itemsFor(lang: string): T[] {
		state.i18n[lang] ??= [];
		return state.i18n[lang];
	}
</script>

<div>
	<div class="ceI18nToggle">
		<input type="checkbox" class="ceCheckbox" id={toggleId} bind:checked={state.useI18n} />
		<label for={toggleId} class="ceToggleLabel">Enable multilingual support</label>
	</div>

	{#if state.useI18n}
		<div class="ceI18nTabs">
			<button
				type="button"
				class="ceI18nTab"
				class:ceI18nTabActive={currentLang === 'default'}
				onclick={() => (activeLang = null)}
			>
				Default (EN)
			</button>
			{#each langs as code (code)}
				<button
					type="button"
					class="ceI18nTab"
					class:ceI18nTabActive={currentLang === code}
					onclick={() => (activeLang = code)}
				>
					{languageList.find(([c]) => c === code)?.[1] ?? code}
				</button>
			{/each}
		</div>
		{#if currentLang === 'default'}
			{@render renderItems(state.items, 'default')}
		{:else}
			{@render renderItems(itemsFor(currentLang), currentLang)}
		{/if}
	{:else}
		{@render renderItems(state.items, 'default')}
	{/if}
</div>
