// docs/src/components/ConfigEditor/sections/InterfaceSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import styles from '../ConfigEditor.module.css';

export default function InterfaceSection() {
  const { state } = useConfigEditor();
  const { set } = useFieldSetter(['INTERFACE']);

  return (
    <AccordionSection
      id="section-interface"
      title="Interface"
      description="User interface behavior: theme preference, phone removal, panel switching, and target selector options."
      learnMoreHref="./guide-for-admins/customize-page#interface"
    >
      <div className={styles.ceFieldGroup}>
        <label className={styles.ceLabel}>Theme Preference</label>
        <select
          className={styles.ceSelect}
          value={state.INTERFACE.PREFERRED_DARK_MODE_THEME}
          onChange={(e) => set('PREFERRED_DARK_MODE_THEME', e.target.value)}
        >
          <option value="light">Light</option>
          <option value="dark">Dark</option>
          <option value="system">System</option>
        </select>
      </div>

      <div className={styles.ceToggleRow}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={state.INTERFACE.ALLOW_REMOVING_PHONE_FROM_SELECTOR}
          onChange={(e) => set('ALLOW_REMOVING_PHONE_FROM_SELECTOR', e.target.checked)}
          id="if-allow-remove"
        />
        <label htmlFor="if-allow-remove" className={styles.ceToggleLabel}>
          Allow removing phone from selector
        </label>
      </div>

      <div className={styles.ceToggleRow}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={state.INTERFACE.SWITCH_PHONE_PANEL_ON_BRAND_CLICK}
          onChange={(e) => set('SWITCH_PHONE_PANEL_ON_BRAND_CLICK', e.target.checked)}
          id="if-switch-panel"
        />
        <label htmlFor="if-switch-panel" className={styles.ceToggleLabel}>
          Switch to phone panel on brand click (mobile)
        </label>
      </div>

      <div className={styles.ceSubSection}>
        <div className={styles.ceSubSectionTitle}>Target Selector</div>

        <div className={styles.ceToggleRow}>
          <input
            type="checkbox"
            className={styles.ceCheckbox}
            checked={state.INTERFACE.TARGET.ALLOW_MULTIPLE_LINE_PER_TYPE}
            onChange={(e) => set(['TARGET', 'ALLOW_MULTIPLE_LINE_PER_TYPE'], e.target.checked)}
            id="if-target-multi"
          />
          <label htmlFor="if-target-multi" className={styles.ceToggleLabel}>
            Multiple lines per type
          </label>
        </div>

        <div className={styles.ceToggleRow}>
          <input
            type="checkbox"
            className={styles.ceCheckbox}
            checked={state.INTERFACE.TARGET.OMIT_TARGET_SUFFIX}
            onChange={(e) => set(['TARGET', 'OMIT_TARGET_SUFFIX'], e.target.checked)}
            id="if-target-suffix"
          />
          <label htmlFor="if-target-suffix" className={styles.ceToggleLabel}>
            Omit "Target" suffix
          </label>
        </div>

        <div className={styles.ceToggleRow}>
          <input
            type="checkbox"
            className={styles.ceCheckbox}
            checked={state.INTERFACE.TARGET.COLLAPSE_TARGET_LIST_ON_INITIAL}
            onChange={(e) => set(['TARGET', 'COLLAPSE_TARGET_LIST_ON_INITIAL'], e.target.checked)}
            id="if-target-collapse"
          />
          <label htmlFor="if-target-collapse" className={styles.ceToggleLabel}>
            Collapse target list on initial load
          </label>
        </div>
      </div>

      <div className={styles.ceToggleRow}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={state.INTERFACE.HIDE_DEV_DONATE_BUTTON}
          onChange={(e) => set('HIDE_DEV_DONATE_BUTTON', e.target.checked)}
          id="if-hide-donate"
        />
        <label htmlFor="if-hide-donate" className={styles.ceToggleLabel}>
          Hide donate button
        </label>
      </div>
    </AccordionSection>
  );
}

// docs/src/components/tools/config-editor/sections/InterfaceSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';

	let config = $derived(configEditor.config);
	const id = $props.id();
</script>

<AccordionSection
	id="section-interface"
	title="Interface"
	description="User interface behavior: theme preference, phone removal, panel switching, and target selector options."
	learnMoreHref="./guide-for-admins/customize-page#interface"
>
	<div class="ceFieldGroup">
		<label class="ceLabel" for="{id}-theme">Theme Preference</label>
		<select
			id="{id}-theme"
			class="ceSelect"
			bind:value={config.INTERFACE.PREFERRED_DARK_MODE_THEME}
		>
			<option value="light">Light</option>
			<option value="dark">Dark</option>
			<option value="system">System</option>
		</select>
	</div>

	<div class="ceToggleRow">
		<input
			type="checkbox"
			class="ceCheckbox"
			bind:checked={config.INTERFACE.ALLOW_REMOVING_PHONE_FROM_SELECTOR}
			id="{id}-allow-remove"
		/>
		<label for="{id}-allow-remove" class="ceToggleLabel">
			Allow removing phone from selector
		</label>
	</div>

	<div class="ceToggleRow">
		<input
			type="checkbox"
			class="ceCheckbox"
			bind:checked={config.INTERFACE.SWITCH_PHONE_PANEL_ON_BRAND_CLICK}
			id="{id}-switch-panel"
		/>
		<label for="{id}-switch-panel" class="ceToggleLabel">
			Switch to phone panel on brand click (mobile)
		</label>
	</div>

	<div class="ceSubSection">
		<div class="ceSubSectionTitle">Target Selector</div>

		<div class="ceToggleRow">
			<input
				type="checkbox"
				class="ceCheckbox"
				bind:checked={config.INTERFACE.TARGET.ALLOW_MULTIPLE_LINE_PER_TYPE}
				id="{id}-target-multi"
			/>
			<label for="{id}-target-multi" class="ceToggleLabel">Multiple lines per type</label>
		</div>

		<div class="ceToggleRow">
			<input
				type="checkbox"
				class="ceCheckbox"
				bind:checked={config.INTERFACE.TARGET.OMIT_TARGET_SUFFIX}
				id="{id}-target-suffix"
			/>
			<label for="{id}-target-suffix" class="ceToggleLabel">Omit "Target" suffix</label>
		</div>

		<div class="ceToggleRow">
			<input
				type="checkbox"
				class="ceCheckbox"
				bind:checked={config.INTERFACE.TARGET.COLLAPSE_TARGET_LIST_ON_INITIAL}
				id="{id}-target-collapse"
			/>
			<label for="{id}-target-collapse" class="ceToggleLabel">
				Collapse target list on initial load
			</label>
		</div>
	</div>

	<div class="ceToggleRow">
		<input
			type="checkbox"
			class="ceCheckbox"
			bind:checked={config.INTERFACE.HIDE_DEV_DONATE_BUTTON}
			id="{id}-hide-donate"
		/>
		<label for="{id}-hide-donate" class="ceToggleLabel">Hide donate button</label>
	</div>
</AccordionSection>
