// docs/src/components/ConfigEditor/sections/TargetCustomizerSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import StringArrayEditor from '../shared/StringArrayEditor';
import type {
	FilterForm,
	FilterPresetForm,
	InitialTargetFilterForm
} from '@site/src/utils/configDefaults';
import styles from '../ConfigEditor.module.css';

const FILTER_TYPES = ['TILT', 'LSQ', 'HSQ', 'PK'];

export default function TargetCustomizerSection() {
	const { state, dispatch } = useConfigEditor();
	const { set } = useFieldSetter(['TARGET_CUSTOMIZER']);

	const filters = state.TARGET_CUSTOMIZER.FILTERS;
	const presets = state.TARGET_CUSTOMIZER.FILTER_PRESET;
	const initialFilters = state.TARGET_CUSTOMIZER.INITIAL_TARGET_FILTERS;

	// ── Filter helpers ──────────────────────────────────────────────────────

	const updateFilter = (index: number, partial: Partial<FilterForm>) => {
		const copy = filters.map((f) => ({ ...f }));
		copy[index] = { ...copy[index], ...partial };
		set('FILTERS', copy);
	};

	const updateFilterDescription = (index: number, value: string) => {
		const copy = filters.map((f) => ({ ...f }));
		if (value) {
			copy[index] = { ...copy[index], description: value };
		} else {
			const { description, ...rest } = copy[index];
			copy[index] = rest as FilterForm;
		}
		set('FILTERS', copy);
	};

	const removeFilter = (index: number) => {
		set(
			'FILTERS',
			filters.filter((_, i) => i !== index)
		);
	};

	const addFilter = () => {
		set('FILTERS', [...filters, { id: '', name: '', type: 'PK', freq: 0, q: 0 }]);
	};

	// ── Preset helpers ──────────────────────────────────────────────────────

	const updatePreset = (index: number, partial: Partial<FilterPresetForm>) => {
		const copy = presets.map((p) => ({ ...p, filter: { ...p.filter } }));
		copy[index] = { ...copy[index], ...partial };
		set('FILTER_PRESET', copy);
	};

	const updatePresetFilter = (presetIndex: number, filterId: string, value: string) => {
		const copy = presets.map((p) => ({ ...p, filter: { ...p.filter } }));
		if (value === '' || value === undefined) {
			delete copy[presetIndex].filter[filterId];
		} else {
			copy[presetIndex].filter[filterId] = Number(value);
		}
		set('FILTER_PRESET', copy);
	};

	const removePreset = (index: number) => {
		set(
			'FILTER_PRESET',
			presets.filter((_, i) => i !== index)
		);
	};

	const addPreset = () => {
		set('FILTER_PRESET', [...presets, { name: '', filter: {} }]);
	};

	// ── Initial filter helpers ──────────────────────────────────────────────

	const updateInitialFilter = (index: number, partial: Partial<InitialTargetFilterForm>) => {
		const copy = initialFilters.map((f) => ({ ...f, filter: { ...f.filter } }));
		copy[index] = { ...copy[index], ...partial };
		set('INITIAL_TARGET_FILTERS', copy);
	};

	const updateInitialFilterValue = (entryIndex: number, filterId: string, value: string) => {
		const copy = initialFilters.map((f) => ({ ...f, filter: { ...f.filter } }));
		if (value === '' || value === undefined) {
			delete copy[entryIndex].filter[filterId];
		} else {
			copy[entryIndex].filter[filterId] = Number(value);
		}
		set('INITIAL_TARGET_FILTERS', copy);
	};

	const removeInitialFilter = (index: number) => {
		set(
			'INITIAL_TARGET_FILTERS',
			initialFilters.filter((_, i) => i !== index)
		);
	};

	const addInitialFilter = () => {
		set('INITIAL_TARGET_FILTERS', [...initialFilters, { name: '', filter: {} }]);
	};

	// ── Filter gain editor (shared by preset and initial) ──────────────────

	const FilterGainEditor = ({
		filterObj,
		onUpdate
	}: {
		filterObj: Record<string, number>;
		onUpdate: (filterId: string, value: string) => void;
	}) => (
		<div className={styles.ceCardGrid}>
			{filters.map((f) => (
				<div key={f.id} style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
					<span style={{ fontSize: '0.75rem', minWidth: '40px' }}>{f.name || f.id}</span>
					<input
						type="number"
						className={`${styles.ceInput} ${styles.ceInputSmall}`}
						value={filterObj[f.id] ?? ''}
						onChange={(e) => onUpdate(f.id, e.target.value)}
						placeholder="0"
						step={f.type === 'TILT' ? 0.1 : 0.5}
						style={{ width: '80px' }}
					/>
				</div>
			))}
		</div>
	);

	return (
		<AccordionSection
			id="section-target-customizer"
			title="Target Customizer"
			description="Per-target filter adjustments for specified target curves. Define available filters, presets, and initial filter values."
			learnMoreHref="./guide-for-admins/customize-page#target_customizer"
			optional
			enabled={state.TARGET_CUSTOMIZER_ENABLED}
			onToggleEnabled={(v) =>
				dispatch({ type: 'SET_FIELD', path: ['TARGET_CUSTOMIZER_ENABLED'], value: v })
			}
		>
			{/* Customizable Targets */}
			<div className={styles.ceFieldGroup}>
				<label className={styles.ceLabel}>Customizable Targets</label>
				<StringArrayEditor
					items={state.TARGET_CUSTOMIZER.CUSTOMIZABLE_TARGETS}
					onChange={(items) => set('CUSTOMIZABLE_TARGETS', items)}
					placeholder="Target file name"
					addLabel="+ Add target"
				/>
			</div>

			{/* Filters */}
			<div className={styles.ceSubSection}>
				<div className={styles.ceSubSectionTitle}>Filters</div>
				{filters.map((f, i) => (
					<div key={i} className={styles.ceCard}>
						<div className={styles.ceCardHeader}>
							<span className={styles.ceCardTitle}>{f.name || `Filter #${i + 1}`}</span>
							<button
								type="button"
								className={`${styles.ceBtn} ${styles.ceBtnSmall} ${styles.ceBtnDanger}`}
								onClick={() => removeFilter(i)}
							>
								Remove
							</button>
						</div>
						<div className={styles.ceCardGrid}>
							<div className={styles.ceFieldGroup}>
								<label className={styles.ceLabel}>ID</label>
								<input
									type="text"
									className={`${styles.ceInput} ${styles.ceInputSmall}`}
									value={f.id}
									onChange={(e) => updateFilter(i, { id: e.target.value })}
									placeholder="tilt"
								/>
							</div>
							<div className={styles.ceFieldGroup}>
								<label className={styles.ceLabel}>Name</label>
								<input
									type="text"
									className={`${styles.ceInput} ${styles.ceInputSmall}`}
									value={f.name}
									onChange={(e) => updateFilter(i, { name: e.target.value })}
									placeholder="Tilt"
								/>
							</div>
							<div className={styles.ceFieldGroup}>
								<label className={styles.ceLabel}>Type</label>
								<select
									className={styles.ceSelect}
									value={f.type}
									onChange={(e) => updateFilter(i, { type: e.target.value })}
								>
									{FILTER_TYPES.map((t) => (
										<option key={t} value={t}>
											{t}
										</option>
									))}
								</select>
							</div>
							<div className={styles.ceFieldGroup}>
								<label className={styles.ceLabel}>Freq (Hz)</label>
								<input
									type="number"
									className={`${styles.ceInput} ${styles.ceInputSmall}`}
									value={f.freq}
									onChange={(e) => updateFilter(i, { freq: Number(e.target.value) })}
									min={0}
								/>
							</div>
							<div className={styles.ceFieldGroup}>
								<label className={styles.ceLabel}>Q</label>
								<input
									type="number"
									className={`${styles.ceInput} ${styles.ceInputSmall}`}
									value={f.q}
									onChange={(e) => updateFilter(i, { q: Number(e.target.value) })}
									min={0}
									step={0.001}
								/>
							</div>
						</div>
						<div className={styles.ceFieldGroup}>
							<label className={styles.ceLabel}>
								Description
								<span className={styles.ceLabelHint}>optional</span>
							</label>
							<input
								type="text"
								className={styles.ceInput}
								value={f.description ?? ''}
								onChange={(e) => updateFilterDescription(i, e.target.value)}
								placeholder="Bass Filter from Harman MoA 2025 study"
							/>
						</div>
					</div>
				))}
				<button type="button" className={styles.ceArrayAddBtn} onClick={addFilter}>
					+ Add filter
				</button>
			</div>

			{/* Filter Presets */}
			<div className={styles.ceSubSection}>
				<div className={styles.ceSubSectionTitle}>Filter Presets</div>
				{presets.map((p, i) => (
					<div key={i} className={styles.ceCard}>
						<div className={styles.ceCardHeader}>
							<span className={styles.ceCardTitle}>{p.name || `Preset #${i + 1}`}</span>
							<button
								type="button"
								className={`${styles.ceBtn} ${styles.ceBtnSmall} ${styles.ceBtnDanger}`}
								onClick={() => removePreset(i)}
							>
								Remove
							</button>
						</div>
						<div className={styles.ceFieldGroup}>
							<label className={styles.ceLabel}>Name</label>
							<input
								type="text"
								className={styles.ceInput}
								value={p.name}
								onChange={(e) => updatePreset(i, { name: e.target.value })}
								placeholder="Harman 2018"
							/>
						</div>
						<div className={styles.ceFieldGroup}>
							<label className={styles.ceLabel}>Gain Values</label>
							<FilterGainEditor
								filterObj={p.filter}
								onUpdate={(id, val) => updatePresetFilter(i, id, val)}
							/>
						</div>
					</div>
				))}
				<button type="button" className={styles.ceArrayAddBtn} onClick={addPreset}>
					+ Add preset
				</button>
			</div>

			{/* Initial Target Filters */}
			<div className={styles.ceSubSection}>
				<div className={styles.ceSubSectionTitle}>Initial Target Filters</div>
				{initialFilters.map((entry, i) => (
					<div key={i} className={styles.ceCard}>
						<div className={styles.ceCardHeader}>
							<span className={styles.ceCardTitle}>{entry.name || `Entry #${i + 1}`}</span>
							<button
								type="button"
								className={`${styles.ceBtn} ${styles.ceBtnSmall} ${styles.ceBtnDanger}`}
								onClick={() => removeInitialFilter(i)}
							>
								Remove
							</button>
						</div>
						<div className={styles.ceFieldGroup}>
							<label className={styles.ceLabel}>Target Name</label>
							<input
								type="text"
								className={styles.ceInput}
								value={entry.name}
								onChange={(e) => updateInitialFilter(i, { name: e.target.value })}
								placeholder="KEMAR DF (KB006x)"
							/>
						</div>
						<div className={styles.ceFieldGroup}>
							<label className={styles.ceLabel}>Filter Values</label>
							<FilterGainEditor
								filterObj={entry.filter}
								onUpdate={(id, val) => updateInitialFilterValue(i, id, val)}
							/>
						</div>
					</div>
				))}
				<button type="button" className={styles.ceArrayAddBtn} onClick={addInitialFilter}>
					+ Add initial filter
				</button>
			</div>
		</AccordionSection>
	);
}

// docs/src/components/tools/config-editor/sections/TargetCustomizerSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';
	import StringArrayEditor from '../shared/StringArrayEditor.svelte';

	const FILTER_TYPES = ['TILT', 'LSQ', 'HSQ', 'PK'];

	let config = $derived(configEditor.config);
	let tc = $derived(config.TARGET_CUSTOMIZER);
	let filters = $derived(tc.FILTERS);
	const id = $props.id();

	/**
	 * `description` is optional and must disappear from the emitted config when
	 * blanked, not persist as `description: ''` — `configConverter` writes back
	 * whatever key is present.
	 */
	function setDescription(index: number, value: string) {
		if (value) {
			filters[index].description = value;
		} else {
			delete filters[index].description;
		}
	}

	/** Gain of `''` means "this preset does not touch this filter", so drop the key. */
	function setGain(filterObj: Record<string, number>, filterId: string, raw: string) {
		if (raw === '') {
			delete filterObj[filterId];
		} else {
			filterObj[filterId] = Number(raw);
		}
	}
</script>

<!--
	Shared by the preset and initial-filter cards. The React version declared
	this as a component inside the section body, which gave it a fresh identity
	on every render and made each keystroke remount the inputs; a snippet has no
	such problem.
-->
{#snippet filterGainEditor(filterObj: Record<string, number>, scope: string)}
	<div class="ceCardGrid">
		{#each filters as f (f.id)}
			<div style="display: flex; align-items: center; gap: 0.375rem;">
				<label style="font-size: 0.75rem; min-width: 40px;" for="{scope}-gain-{f.id}">
					{f.name || f.id}
				</label>
				<input
					id="{scope}-gain-{f.id}"
					type="number"
					class="ceInput ceInputSmall"
					value={filterObj[f.id] ?? ''}
					oninput={(e) => setGain(filterObj, f.id, e.currentTarget.value)}
					placeholder="0"
					step={f.type === 'TILT' ? 0.1 : 0.5}
					style="width: 80px;"
				/>
			</div>
		{/each}
	</div>
{/snippet}

<AccordionSection
	id="section-target-customizer"
	title="Target Customizer"
	description="Per-target filter adjustments for specified target curves. Define available filters, presets, and initial filter values."
	learnMoreHref="./guide-for-admins/customize-page#target_customizer"
	optional
	bind:enabled={config.TARGET_CUSTOMIZER_ENABLED}
>
	<!-- Customizable Targets -->
	<div class="ceFieldGroup">
		<span class="ceLabel">Customizable Targets</span>
		<StringArrayEditor
			bind:items={tc.CUSTOMIZABLE_TARGETS}
			placeholder="Target file name"
			addLabel="+ Add target"
		/>
	</div>

	<!-- Filters -->
	<div class="ceSubSection">
		<div class="ceSubSectionTitle">Filters</div>
		{#each filters as f, i (i)}
			<div class="ceCard">
				<div class="ceCardHeader">
					<span class="ceCardTitle">{f.name || `Filter #${i + 1}`}</span>
					<button
						type="button"
						class="ceBtn ceBtnSmall ceBtnDanger"
						onclick={() => filters.splice(i, 1)}
					>
						Remove
					</button>
				</div>
				<div class="ceCardGrid">
					<div class="ceFieldGroup">
						<label class="ceLabel" for="{id}-f{i}-id">ID</label>
						<input
							id="{id}-f{i}-id"
							type="text"
							class="ceInput ceInputSmall"
							bind:value={f.id}
							placeholder="tilt"
						/>
					</div>
					<div class="ceFieldGroup">
						<label class="ceLabel" for="{id}-f{i}-name">Name</label>
						<input
							id="{id}-f{i}-name"
							type="text"
							class="ceInput ceInputSmall"
							bind:value={f.name}
							placeholder="Tilt"
						/>
					</div>
					<div class="ceFieldGroup">
						<label class="ceLabel" for="{id}-f{i}-type">Type</label>
						<select id="{id}-f{i}-type" class="ceSelect" bind:value={f.type}>
							{#each FILTER_TYPES as t (t)}
								<option value={t}>{t}</option>
							{/each}
						</select>
					</div>
					<div class="ceFieldGroup">
						<label class="ceLabel" for="{id}-f{i}-freq">Freq (Hz)</label>
						<input
							id="{id}-f{i}-freq"
							type="number"
							class="ceInput ceInputSmall"
							bind:value={f.freq}
							min="0"
						/>
					</div>
					<div class="ceFieldGroup">
						<label class="ceLabel" for="{id}-f{i}-q">Q</label>
						<input
							id="{id}-f{i}-q"
							type="number"
							class="ceInput ceInputSmall"
							bind:value={f.q}
							min="0"
							step="0.001"
						/>
					</div>
				</div>
				<div class="ceFieldGroup">
					<label class="ceLabel" for="{id}-f{i}-desc">
						Description
						<span class="ceLabelHint">optional</span>
					</label>
					<input
						id="{id}-f{i}-desc"
						type="text"
						class="ceInput"
						value={f.description ?? ''}
						oninput={(e) => setDescription(i, e.currentTarget.value)}
						placeholder="Bass Filter from Harman MoA 2025 study"
					/>
				</div>
			</div>
		{/each}
		<button
			type="button"
			class="ceArrayAddBtn"
			onclick={() => filters.push({ id: '', name: '', type: 'PK', freq: 0, q: 0 })}
		>
			+ Add filter
		</button>
	</div>

	<!-- Filter Presets -->
	<div class="ceSubSection">
		<div class="ceSubSectionTitle">Filter Presets</div>
		{#each tc.FILTER_PRESET as p, i (i)}
			<div class="ceCard">
				<div class="ceCardHeader">
					<span class="ceCardTitle">{p.name || `Preset #${i + 1}`}</span>
					<button
						type="button"
						class="ceBtn ceBtnSmall ceBtnDanger"
						onclick={() => tc.FILTER_PRESET.splice(i, 1)}
					>
						Remove
					</button>
				</div>
				<div class="ceFieldGroup">
					<label class="ceLabel" for="{id}-p{i}-name">Name</label>
					<input
						id="{id}-p{i}-name"
						type="text"
						class="ceInput"
						bind:value={p.name}
						placeholder="Harman 2018"
					/>
				</div>
				<div class="ceFieldGroup">
					<span class="ceLabel">Gain Values</span>
					{@render filterGainEditor(p.filter, `${id}-p${i}`)}
				</div>
			</div>
		{/each}
		<button
			type="button"
			class="ceArrayAddBtn"
			onclick={() => tc.FILTER_PRESET.push({ name: '', filter: {} })}
		>
			+ Add preset
		</button>
	</div>

	<!-- Initial Target Filters -->
	<div class="ceSubSection">
		<div class="ceSubSectionTitle">Initial Target Filters</div>
		{#each tc.INITIAL_TARGET_FILTERS as entry, i (i)}
			<div class="ceCard">
				<div class="ceCardHeader">
					<span class="ceCardTitle">{entry.name || `Entry #${i + 1}`}</span>
					<button
						type="button"
						class="ceBtn ceBtnSmall ceBtnDanger"
						onclick={() => tc.INITIAL_TARGET_FILTERS.splice(i, 1)}
					>
						Remove
					</button>
				</div>
				<div class="ceFieldGroup">
					<label class="ceLabel" for="{id}-i{i}-name">Target Name</label>
					<input
						id="{id}-i{i}-name"
						type="text"
						class="ceInput"
						bind:value={entry.name}
						placeholder="KEMAR DF (KB006x)"
					/>
				</div>
				<div class="ceFieldGroup">
					<span class="ceLabel">Filter Values</span>
					{@render filterGainEditor(entry.filter, `${id}-i${i}`)}
				</div>
			</div>
		{/each}
		<button
			type="button"
			class="ceArrayAddBtn"
			onclick={() => tc.INITIAL_TARGET_FILTERS.push({ name: '', filter: {} })}
		>
			+ Add initial filter
		</button>
	</div>
</AccordionSection>
