// docs/src/components/ConfigEditor/sections/UrlSection.tsx
import React from 'react';
import { useConfigEditor, useFieldSetter } from '../ConfigEditorContext';
import AccordionSection from '../shared/AccordionSection';
import styles from '../ConfigEditor.module.css';

export default function UrlSection() {
  const { state } = useConfigEditor();
  const { set } = useFieldSetter(['URL']);

  return (
    <AccordionSection
      id="section-url"
      title="URL"
      description="Controls whether the URL auto-updates with selected devices/targets and whether it's compressed."
      learnMoreHref="./guide-for-admins/customize-page#url"
    >
      <div className={styles.ceToggleRow}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={state.URL.AUTO_UPDATE_URL}
          onChange={(e) => set('AUTO_UPDATE_URL', e.target.checked)}
          id="url-auto-update"
        />
        <label htmlFor="url-auto-update" className={styles.ceToggleLabel}>
          Auto-update URL
          <span className={styles.ceToggleHint}>Update URL when phones/targets change</span>
        </label>
      </div>

      <div className={styles.ceToggleRow}>
        <input
          type="checkbox"
          className={styles.ceCheckbox}
          checked={state.URL.COMPRESS_URL}
          onChange={(e) => set('COMPRESS_URL', e.target.checked)}
          id="url-compress"
        />
        <label htmlFor="url-compress" className={styles.ceToggleLabel}>
          Compress URL
          <span className={styles.ceToggleHint}>Uses Base62 encoding</span>
        </label>
      </div>
    </AccordionSection>
  );
}

// docs/src/components/tools/config-editor/sections/UrlSection.svelte
<script lang="ts">
	import { configEditor } from '../config-store.svelte';
	import AccordionSection from '../shared/AccordionSection.svelte';

	let config = $derived(configEditor.config);
	const id = $props.id();
</script>

<AccordionSection
	id="section-url"
	title="URL"
	description="Controls whether the URL auto-updates with selected devices/targets and whether it's compressed."
	learnMoreHref="./guide-for-admins/customize-page#url"
>
	<div class="ceToggleRow">
		<input
			type="checkbox"
			class="ceCheckbox"
			bind:checked={config.URL.AUTO_UPDATE_URL}
			id="{id}-auto-update"
		/>
		<label for="{id}-auto-update" class="ceToggleLabel">
			Auto-update URL
			<span class="ceToggleHint">Update URL when phones/targets change</span>
		</label>
	</div>

	<div class="ceToggleRow">
		<input
			type="checkbox"
			class="ceCheckbox"
			bind:checked={config.URL.COMPRESS_URL}
			id="{id}-compress"
		/>
		<label for="{id}-compress" class="ceToggleLabel">
			Compress URL
			<span class="ceToggleHint">Uses Base62 encoding</span>
		</label>
	</div>
</AccordionSection>
