// docs/src/components/ConfigEditor/ExportBar.tsx
import React, { useState, useMemo, type ReactNode } from 'react';
import { useConfigEditor } from './ConfigEditorContext';
import { formStateToConfigString } from '@site/src/utils/configConverter';
import styles from './ConfigEditor.module.css';

export default function ExportBar(): ReactNode {
  const { state } = useConfigEditor();
  const [showPreview, setShowPreview] = useState(false);
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => formStateToConfigString(state), [state]);

  const handleDownload = () => {
    const blob = new Blob([output], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'config.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = output;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div>
      <div className={styles.ceExportBar}>
        <button type="button" className={`${styles.ceBtn} ${styles.ceBtnPrimary}`} onClick={handleDownload}>
          Download config.js
        </button>
        <button type="button" className={styles.ceBtn} onClick={handleCopy}>
          {copied ? 'Copied!' : 'Copy to clipboard'}
        </button>
        <button
          type="button"
          className={styles.ceBtn}
          onClick={() => setShowPreview((p) => !p)}
        >
          {showPreview ? 'Hide preview' : 'Preview output'}
        </button>
      </div>

      {showPreview && (
        <div className={styles.ceExportPreview}>
          <textarea
            className={styles.ceExportTextarea}
            value={output}
            readOnly
            spellCheck={false}
          />
        </div>
      )}
    </div>
  );
}

// docs/src/components/tools/config-editor/ExportBar.svelte
<script lang="ts">
	import { configEditor } from './config-store.svelte';
	import { formStateToConfigString } from '../../../utils/configConverter';

	let showPreview = $state(false);
	let copied = $state(false);

	/*
	 * `$derived` replaces the React `useMemo`. Because `$state` is deeply
	 * reactive, this re-runs on any field edit anywhere in the form without the
	 * dependency array the memo needed — which had to be the whole state object,
	 * and so recomputed on every keystroke anyway.
	 */
	let output = $derived(formStateToConfigString(configEditor.config));

	function handleDownload() {
		const blob = new Blob([output], { type: 'application/javascript' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'config.js';
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}

	async function handleCopy() {
		try {
			await navigator.clipboard.writeText(output);
		} catch {
			// Fallback
			const textarea = document.createElement('textarea');
			textarea.value = output;
			document.body.appendChild(textarea);
			textarea.select();
			document.execCommand('copy');
			document.body.removeChild(textarea);
		}
		copied = true;
		setTimeout(() => (copied = false), 2000);
	}
</script>

<div>
	<div class="ceExportBar">
		<button type="button" class="ceBtn ceBtnPrimary" onclick={handleDownload}>
			Download config.js
		</button>
		<button type="button" class="ceBtn" onclick={handleCopy}>
			{copied ? 'Copied!' : 'Copy to clipboard'}
		</button>
		<button type="button" class="ceBtn" onclick={() => (showPreview = !showPreview)}>
			{showPreview ? 'Hide preview' : 'Preview output'}
		</button>
	</div>

	{#if showPreview}
		<div class="ceExportPreview">
			<textarea
				class="ceExportTextarea"
				aria-label="Generated config.js"
				value={output}
				readonly
				spellcheck="false"></textarea>
		</div>
	{/if}
</div>
